# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.34-dev.9866
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.game_post_enrichment import GamePostEnrichment


class TestGamePostEnrichment(unittest.TestCase):
    """GamePostEnrichment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GamePostEnrichment:
        """Test GamePostEnrichment
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GamePostEnrichment`
        """
        model = GamePostEnrichment()
        if include_optional:
            return GamePostEnrichment(
                school_id = 56,
                sport_id = 56,
                schedule_intents = [
                    winthrop_client_python.models.game_post_enrichment_schedule_intents_inner.GamePostEnrichment_schedule_intents_inner(
                        id = 56, 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        game_types = [
                            ''
                            ], )
                    ],
                overlap = winthrop_client_python.models.game_post_enrichment_overlap.GamePostEnrichment_overlap(
                    total = 56, 
                    strong_count = 56, 
                    rollup_text = '', 
                    line_ups = [
                        winthrop_client_python.models.game_post_enrichment_overlap_line_ups_inner.GamePostEnrichment_overlap_line_ups_inner(
                            date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            classification = 'guarantee', 
                            strong = True, 
                            traveling_school_id = 56, 
                            hosting_school_id = 56, 
                            traveling_school_name = '', 
                            hosting_school_name = '', 
                            possible_kind = 'both_host', 
                            flexible_side = 'viewer', 
                            viewer_wants = [
                                'GuaranteeOffered'
                                ], 
                            poster_wants = [
                                'GuaranteeOffered'
                                ], )
                        ], ),
                guarantee = winthrop_client_python.models.game_post_enrichment_guarantee.GamePostEnrichment_guarantee(
                    host_median_cents = 56, 
                    host_sample_size = 56, 
                    travel_median_cents = 56, 
                    travel_sample_size = 56, )
            )
        else:
            return GamePostEnrichment(
                school_id = 56,
                sport_id = 56,
                schedule_intents = [
                    winthrop_client_python.models.game_post_enrichment_schedule_intents_inner.GamePostEnrichment_schedule_intents_inner(
                        id = 56, 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        game_types = [
                            ''
                            ], )
                    ],
                overlap = winthrop_client_python.models.game_post_enrichment_overlap.GamePostEnrichment_overlap(
                    total = 56, 
                    strong_count = 56, 
                    rollup_text = '', 
                    line_ups = [
                        winthrop_client_python.models.game_post_enrichment_overlap_line_ups_inner.GamePostEnrichment_overlap_line_ups_inner(
                            date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            classification = 'guarantee', 
                            strong = True, 
                            traveling_school_id = 56, 
                            hosting_school_id = 56, 
                            traveling_school_name = '', 
                            hosting_school_name = '', 
                            possible_kind = 'both_host', 
                            flexible_side = 'viewer', 
                            viewer_wants = [
                                'GuaranteeOffered'
                                ], 
                            poster_wants = [
                                'GuaranteeOffered'
                                ], )
                        ], ),
        )
        """

    def testGamePostEnrichment(self):
        """Test GamePostEnrichment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
