# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.29722074251
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.job_progress import JobProgress


class TestJobProgress(unittest.TestCase):
    """JobProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobProgress:
        """Test JobProgress
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `JobProgress`
        """
        model = JobProgress()
        if include_optional:
            return JobProgress(
                pages_done = 56
            )
        else:
            return JobProgress(
        )
        """

    def testJobProgress(self):
        """Test JobProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
