# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.0-dev.10377
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.desk_admin_cover import DeskAdminCover


class TestDeskAdminCover(unittest.TestCase):
    """DeskAdminCover unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeskAdminCover:
        """Test DeskAdminCover
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeskAdminCover`
        """
        model = DeskAdminCover()
        if include_optional:
            return DeskAdminCover(
                title = '',
                category = 'Financials',
                report_type = 'intelligence_brief',
                summary = '',
                headline_stats = [
                    winthrop_client_python.models.desk_headline_stat.DeskHeadlineStat(
                        value = '', 
                        label = '', )
                    ],
                cover_treatment = 'ink',
                cover_kicker = '',
                cover_numeral = '',
                page_count = 56,
                push_example = '',
                rerun_cadence = 'off'
            )
        else:
            return DeskAdminCover(
        )
        """

    def testDeskAdminCover(self):
        """Test DeskAdminCover"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
