# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.update_school_group_request import (
    UpdateSchoolGroupRequest,
)


class TestUpdateSchoolGroupRequest(unittest.TestCase):
    """UpdateSchoolGroupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSchoolGroupRequest:
        """Test UpdateSchoolGroupRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UpdateSchoolGroupRequest`
        """
        model = UpdateSchoolGroupRequest()
        if include_optional:
            return UpdateSchoolGroupRequest(
                school_group = winthrop_client_python.models.update_school_group_request_school_group.update_school_group_request_school_group(
                    name = '', 
                    school_ids = [
                        56
                        ], )
            )
        else:
            return UpdateSchoolGroupRequest(
                school_group = winthrop_client_python.models.update_school_group_request_school_group.update_school_group_request_school_group(
                    name = '', 
                    school_ids = [
                        56
                        ], ),
        )
        """

    def testUpdateSchoolGroupRequest(self):
        """Test UpdateSchoolGroupRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
