# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.coach_recruiting_tab_recruiting_budgets import (
    CoachRecruitingTabRecruitingBudgets,
)


class TestCoachRecruitingTabRecruitingBudgets(unittest.TestCase):
    """CoachRecruitingTabRecruitingBudgets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoachRecruitingTabRecruitingBudgets:
        """Test CoachRecruitingTabRecruitingBudgets
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CoachRecruitingTabRecruitingBudgets`
        """
        model = CoachRecruitingTabRecruitingBudgets()
        if include_optional:
            return CoachRecruitingTabRecruitingBudgets(
                title = '',
                entries = [
                    winthrop_client_python.models.recruiting_budget_entry.RecruitingBudgetEntry(
                        school_name = '', 
                        school_id = 56, 
                        budget_cents = 56, 
                        class_rank = 56, 
                        conference_record = '', )
                    ]
            )
        else:
            return CoachRecruitingTabRecruitingBudgets(
                title = '',
                entries = [
                    winthrop_client_python.models.recruiting_budget_entry.RecruitingBudgetEntry(
                        school_name = '', 
                        school_id = 56, 
                        budget_cents = 56, 
                        class_rank = 56, 
                        conference_record = '', )
                    ],
        )
        """

    def testCoachRecruitingTabRecruitingBudgets(self):
        """Test CoachRecruitingTabRecruitingBudgets"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
