# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.athletic_profile_show_financial_info import (
    AthleticProfileShowFinancialInfo,
)


class TestAthleticProfileShowFinancialInfo(unittest.TestCase):
    """AthleticProfileShowFinancialInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AthleticProfileShowFinancialInfo:
        """Test AthleticProfileShowFinancialInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AthleticProfileShowFinancialInfo`
        """
        model = AthleticProfileShowFinancialInfo()
        if include_optional:
            return AthleticProfileShowFinancialInfo(
                year = 56,
                total_student_enrollment = 56,
                male_students = 56,
                female_students = 56,
                student_athlete_enrollment = 56,
                male_athletes = 56,
                female_athletes = 56
            )
        else:
            return AthleticProfileShowFinancialInfo(
        )
        """

    def testAthleticProfileShowFinancialInfo(self):
        """Test AthleticProfileShowFinancialInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
