# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.asst_coach_school import AsstCoachSchool


class TestAsstCoachSchool(unittest.TestCase):
    """AsstCoachSchool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AsstCoachSchool:
        """Test AsstCoachSchool
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AsstCoachSchool`
        """
        model = AsstCoachSchool()
        if include_optional:
            return AsstCoachSchool(
                school_id = 56,
                school_name = '',
                pool_total = 56,
                coaches = [
                    winthrop_client_python.models.asst_coach_entry.AsstCoachEntry(
                        id = 56, 
                        coach_name = '', 
                        total_comp = 56, )
                    ]
            )
        else:
            return AsstCoachSchool(
        )
        """

    def testAsstCoachSchool(self):
        """Test AsstCoachSchool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
