# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.coach_profile import CoachProfile


class TestCoachProfile(unittest.TestCase):
    """CoachProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoachProfile:
        """Test CoachProfile
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CoachProfile`
        """
        model = CoachProfile()
        if include_optional:
            return CoachProfile(
                id = 56,
                first_name = '',
                last_name = '',
                email = '',
                phone = '',
                leader = True,
                hometown_city = '',
                hometown_state = '',
                alma_mater_name = '',
                alma_mater_year = 56,
                twitter_handle = '',
                twitter_verified = True,
                linkedin = '',
                linkedin_verified = True,
                instagram_handle = '',
                instagram_verified = True,
                bio = '',
                coach_friendly_id = '',
                departing = True,
                current_school_name = '',
                current_school_id = 56,
                current_sport_name = '',
                current_position_types = [
                    ''
                    ],
                avatar_url = '',
                can_see_compensation = True,
                can_see_videos = True,
                can_see_coworker_history = True,
                is_sport_specific = True
            )
        else:
            return CoachProfile(
                id = 56,
                first_name = '',
                last_name = '',
                leader = True,
                twitter_verified = True,
                linkedin_verified = True,
                instagram_verified = True,
                current_position_types = [
                    ''
                    ],
                can_see_compensation = True,
                can_see_videos = True,
                can_see_coworker_history = True,
                is_sport_specific = True,
        )
        """

    def testCoachProfile(self):
        """Test CoachProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
