# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.55
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.department_overview_dollar_shares import (
    DepartmentOverviewDollarShares,
)


class TestDepartmentOverviewDollarShares(unittest.TestCase):
    """DepartmentOverviewDollarShares unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepartmentOverviewDollarShares:
        """Test DepartmentOverviewDollarShares
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DepartmentOverviewDollarShares`
        """
        model = DepartmentOverviewDollarShares()
        if include_optional:
            return DepartmentOverviewDollarShares(
                total_cents = 56,
                lines = [
                    winthrop_client_python.models.department_overview_share_line.DepartmentOverviewShareLine(
                        key = '', 
                        label = '', 
                        amount_cents = 56, 
                        highlight = True, 
                        share = 1.337, )
                    ]
            )
        else:
            return DepartmentOverviewDollarShares(
                total_cents = 56,
                lines = [
                    winthrop_client_python.models.department_overview_share_line.DepartmentOverviewShareLine(
                        key = '', 
                        label = '', 
                        amount_cents = 56, 
                        highlight = True, 
                        share = 1.337, )
                    ],
        )
        """

    def testDepartmentOverviewDollarShares(self):
        """Test DepartmentOverviewDollarShares"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
