# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.sport_compensation_rankings_schools_inner import (
    SportCompensationRankingsSchoolsInner,
)


class TestSportCompensationRankingsSchoolsInner(unittest.TestCase):
    """SportCompensationRankingsSchoolsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SportCompensationRankingsSchoolsInner:
        """Test SportCompensationRankingsSchoolsInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SportCompensationRankingsSchoolsInner`
        """
        model = SportCompensationRankingsSchoolsInner()
        if include_optional:
            return SportCompensationRankingsSchoolsInner(
                school_id = 56,
                school_name = '',
                avg = 1.337,
                by_year = {
                    'key' : 1.337
                    }
            )
        else:
            return SportCompensationRankingsSchoolsInner(
        )
        """

    def testSportCompensationRankingsSchoolsInner(self):
        """Test SportCompensationRankingsSchoolsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
