# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.6
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.get_raw_contract_ocr_text422_response import (
    GetRawContractOcrText422Response,
)


class TestGetRawContractOcrText422Response(unittest.TestCase):
    """GetRawContractOcrText422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRawContractOcrText422Response:
        """Test GetRawContractOcrText422Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetRawContractOcrText422Response`
        """
        model = GetRawContractOcrText422Response()
        if include_optional:
            return GetRawContractOcrText422Response(
                error = ''
            )
        else:
            return GetRawContractOcrText422Response(
                error = '',
        )
        """

    def testGetRawContractOcrText422Response(self):
        """Test GetRawContractOcrText422Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
