# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.subscription_acceptance import SubscriptionAcceptance


class TestSubscriptionAcceptance(unittest.TestCase):
    """SubscriptionAcceptance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionAcceptance:
        """Test SubscriptionAcceptance
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SubscriptionAcceptance`
        """
        model = SubscriptionAcceptance()
        if include_optional:
            return SubscriptionAcceptance(
                id = 335,
                slug = '3534255',
                account_name = 'Big Ten',
                subscription_type_name = 'Win12',
                annual_price = '$15,995',
                amount_cents = 1599500,
                start_at = 'Tue Jun 25 00:00:00 UTC 2024',
                end_at = 'Fri Jun 25 00:00:00 UTC 2027',
                contract_term = 36,
                contract_term_options = [
                    winthrop_client_python.models.contract_term_option.ContractTermOption(
                        label = '3 years', 
                        value = 36, )
                    ],
                standard_length_contract = True,
                total_price = '$47,984',
                contract_accepted = False,
                raw_contract_attached = True,
                accepted = True,
                errors = [
                    ''
                    ]
            )
        else:
            return SubscriptionAcceptance(
        )
        """

    def testSubscriptionAcceptance(self):
        """Test SubscriptionAcceptance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
