# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.52
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.job_post_disagreement import JobPostDisagreement


class TestJobPostDisagreement(unittest.TestCase):
    """JobPostDisagreement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobPostDisagreement:
        """Test JobPostDisagreement
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `JobPostDisagreement`
        """
        model = JobPostDisagreement()
        if include_optional:
            return JobPostDisagreement(
                job_post_id = 56,
                title = '',
                description = '',
                school_name = '',
                link = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                llm_is_athletics = True,
                ml_is_athletics = True,
                reasoning = '',
                admin_url = '',
                novelty = 'new'
            )
        else:
            return JobPostDisagreement(
        )
        """

    def testJobPostDisagreement(self):
        """Test JobPostDisagreement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
