# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.3-dev.10366
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.athletic_profile_show_sport_financials_program_cost_per_win import (
    AthleticProfileShowSportFinancialsProgramCostPerWin,
)


class TestAthleticProfileShowSportFinancialsProgramCostPerWin(unittest.TestCase):
    """AthleticProfileShowSportFinancialsProgramCostPerWin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> AthleticProfileShowSportFinancialsProgramCostPerWin:
        """Test AthleticProfileShowSportFinancialsProgramCostPerWin
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AthleticProfileShowSportFinancialsProgramCostPerWin`
        """
        model = AthleticProfileShowSportFinancialsProgramCostPerWin()
        if include_optional:
            return AthleticProfileShowSportFinancialsProgramCostPerWin(
                fiscal_year = 56,
                expense_cents = 56,
                wins = 56,
                per_win_cents = 56,
                margin_cents = 56,
                cohort_median_per_win_cents = 56,
                cohort_size = 56,
                cheapest = winthrop_client_python.models.athletic_profile_show_sport_financials_program_cost_per_win_cheapest.AthleticProfileShow_sport_financials_program_cost_per_win_cheapest(
                    school_short_name = '', 
                    per_win_cents = 56, )
            )
        else:
            return AthleticProfileShowSportFinancialsProgramCostPerWin(
        )
        """

    def testAthleticProfileShowSportFinancialsProgramCostPerWin(self):
        """Test AthleticProfileShowSportFinancialsProgramCostPerWin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
