# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.2-dev.10366
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.desk_reports_response import DeskReportsResponse


class TestDeskReportsResponse(unittest.TestCase):
    """DeskReportsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeskReportsResponse:
        """Test DeskReportsResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeskReportsResponse`
        """
        model = DeskReportsResponse()
        if include_optional:
            return DeskReportsResponse(
                meta = winthrop_client_python.models.desk_reports_response_meta.DeskReportsResponse_meta(
                    total_entries = 56, ),
                data = [
                    winthrop_client_python.models.desk_report_summary.DeskReportSummary(
                        uuid = '', 
                        title = '', 
                        category = 'Financials', 
                        report_type = 'intelligence_brief', 
                        summary = '', 
                        headline_stats = [
                            winthrop_client_python.models.desk_headline_stat.DeskHeadlineStat(
                                value = '', 
                                label = '', )
                            ], 
                        cover = winthrop_client_python.models.desk_report_summary_cover.DeskReportSummary_cover(
                            treatment = 'ink', 
                            kicker = '', 
                            numeral = '', ), 
                        published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        page_count = 56, 
                        artifact_kinds = [
                            'pdf'
                            ], 
                        artifacts = [
                            winthrop_client_python.models.desk_report_artifact.DeskReportArtifact(
                                kind = 'pdf', 
                                filename = '', 
                                url = '', )
                            ], 
                        rerun_cadence = 'off', 
                        push_example = '', 
                        unread = True, 
                        archived = True, 
                        request_context = null, )
                    ]
            )
        else:
            return DeskReportsResponse(
                meta = winthrop_client_python.models.desk_reports_response_meta.DeskReportsResponse_meta(
                    total_entries = 56, ),
                data = [
                    winthrop_client_python.models.desk_report_summary.DeskReportSummary(
                        uuid = '', 
                        title = '', 
                        category = 'Financials', 
                        report_type = 'intelligence_brief', 
                        summary = '', 
                        headline_stats = [
                            winthrop_client_python.models.desk_headline_stat.DeskHeadlineStat(
                                value = '', 
                                label = '', )
                            ], 
                        cover = winthrop_client_python.models.desk_report_summary_cover.DeskReportSummary_cover(
                            treatment = 'ink', 
                            kicker = '', 
                            numeral = '', ), 
                        published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        page_count = 56, 
                        artifact_kinds = [
                            'pdf'
                            ], 
                        artifacts = [
                            winthrop_client_python.models.desk_report_artifact.DeskReportArtifact(
                                kind = 'pdf', 
                                filename = '', 
                                url = '', )
                            ], 
                        rerun_cadence = 'off', 
                        push_example = '', 
                        unread = True, 
                        archived = True, 
                        request_context = null, )
                    ],
        )
        """

    def testDeskReportsResponse(self):
        """Test DeskReportsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
