# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.7
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.foia_status_summary_requested_item import (
    FoiaStatusSummaryRequestedItem,
)


class TestFoiaStatusSummaryRequestedItem(unittest.TestCase):
    """FoiaStatusSummaryRequestedItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoiaStatusSummaryRequestedItem:
        """Test FoiaStatusSummaryRequestedItem
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FoiaStatusSummaryRequestedItem`
        """
        model = FoiaStatusSummaryRequestedItem()
        if include_optional:
            return FoiaStatusSummaryRequestedItem(
                requested_item_id = 56,
                requestable_type = '',
                status = 'pending'
            )
        else:
            return FoiaStatusSummaryRequestedItem(
                requested_item_id = 56,
                requestable_type = '',
                status = 'pending',
        )
        """

    def testFoiaStatusSummaryRequestedItem(self):
        """Test FoiaStatusSummaryRequestedItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
