# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.30
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.guarantee_economics_error import (
    GuaranteeEconomicsError,
)


class TestGuaranteeEconomicsError(unittest.TestCase):
    """GuaranteeEconomicsError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GuaranteeEconomicsError:
        """Test GuaranteeEconomicsError
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GuaranteeEconomicsError`
        """
        model = GuaranteeEconomicsError()
        if include_optional:
            return GuaranteeEconomicsError(
                error_type = 'missing_param',
                message = '',
                suggested_fix = '',
                received_args = { }
            )
        else:
            return GuaranteeEconomicsError(
        )
        """

    def testGuaranteeEconomicsError(self):
        """Test GuaranteeEconomicsError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
