# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.get_time_zones200_response import (
    GetTimeZones200Response,
)


class TestGetTimeZones200Response(unittest.TestCase):
    """GetTimeZones200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTimeZones200Response:
        """Test GetTimeZones200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetTimeZones200Response`
        """
        model = GetTimeZones200Response()
        if include_optional:
            return GetTimeZones200Response(
                us_zones = [
                    winthrop_client_python.models.time_zone_option.TimeZoneOption(
                        value = '', 
                        label = '', )
                    ],
                other_zones = [
                    winthrop_client_python.models.time_zone_option.TimeZoneOption(
                        value = '', 
                        label = '', )
                    ]
            )
        else:
            return GetTimeZones200Response(
        )
        """

    def testGetTimeZones200Response(self):
        """Test GetTimeZones200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
