# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.update_account_user_request import (
    UpdateAccountUserRequest,
)


class TestUpdateAccountUserRequest(unittest.TestCase):
    """UpdateAccountUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAccountUserRequest:
        """Test UpdateAccountUserRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UpdateAccountUserRequest`
        """
        model = UpdateAccountUserRequest()
        if include_optional:
            return UpdateAccountUserRequest(
                user = winthrop_client_python.models.update_account_user_request_user.UpdateAccountUserRequest_user(
                    role_symbols = [
                        ''
                        ], 
                    schedule_sport_ids = [
                        56
                        ], 
                    permissible_sport_ids = [
                        56
                        ], )
            )
        else:
            return UpdateAccountUserRequest(
                user = winthrop_client_python.models.update_account_user_request_user.UpdateAccountUserRequest_user(
                    role_symbols = [
                        ''
                        ], 
                    schedule_sport_ids = [
                        56
                        ], 
                    permissible_sport_ids = [
                        56
                        ], ),
        )
        """

    def testUpdateAccountUserRequest(self):
        """Test UpdateAccountUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
