# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.29722074251
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.job_status import JobStatus


class TestJobStatus(unittest.TestCase):
    """JobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobStatus:
        """Test JobStatus
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `JobStatus`
        """
        model = JobStatus()
        if include_optional:
            return JobStatus(
                job_id = '',
                status = '',
                profile = '',
                page_count = 56,
                progress = winthrop_client_python.models.job_progress.JobProgress(
                    pages_done = 56, ),
                created_at = '',
                completed_at = '',
                error = ''
            )
        else:
            return JobStatus(
                job_id = '',
                status = '',
                progress = winthrop_client_python.models.job_progress.JobProgress(
                    pages_done = 56, ),
        )
        """

    def testJobStatus(self):
        """Test JobStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
