# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.40
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.create_job_json import CreateJobJson


class TestCreateJobJson(unittest.TestCase):
    """CreateJobJson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateJobJson:
        """Test CreateJobJson
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateJobJson`
        """
        model = CreateJobJson()
        if include_optional:
            return CreateJobJson(
                source = winthrop_client_python.models.job_source.JobSource(
                    type = '', 
                    file_id = 'z0123456789', ),
                profile = 'default',
                options = winthrop_client_python.models.job_options.JobOptions(
                    force = True, )
            )
        else:
            return CreateJobJson(
                source = winthrop_client_python.models.job_source.JobSource(
                    type = '', 
                    file_id = 'z0123456789', ),
        )
        """

    def testCreateJobJson(self):
        """Test CreateJobJson"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
