# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.38.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from winthrop_client_python.models.deal import Deal


class TestDeal(unittest.TestCase):
    """Deal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Deal:
        """Test Deal
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Deal`
        """
        model = Deal()
        if include_optional:
            return Deal(
                id = 56,
                school_id = 56,
                vendor_id = 56,
                start_at = '2019-01-01T00:00Z',
                end_at = '2019-01-01T00:00Z',
                signed = '2019-01-01T00:00Z',
                created_at = '2019-01-01T00:00Z',
                updated_at = '2019-01-01T00:00Z',
                text = '',
                autorenew = True,
                deal_type_id = 56,
                archived = True,
                deal_status_type_id = 56,
                verified = True
            )
        else:
            return Deal(
        )
        """

    def testDeal(self):
        """Test Deal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
