# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.25
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.foia_follow_up_gmail_search_hints import (
    FoiaFollowUpGmailSearchHints,
)


class TestFoiaFollowUpGmailSearchHints(unittest.TestCase):
    """FoiaFollowUpGmailSearchHints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoiaFollowUpGmailSearchHints:
        """Test FoiaFollowUpGmailSearchHints
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FoiaFollowUpGmailSearchHints`
        """
        model = FoiaFollowUpGmailSearchHints()
        if include_optional:
            return FoiaFollowUpGmailSearchHints(
                canonical_email = '',
                canonical_domain = '',
                admin_parity_first_contact_domain = '',
                lead_email = '',
                lead_domain = '',
                after_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                suggested_query = ''
            )
        else:
            return FoiaFollowUpGmailSearchHints(
        )
        """

    def testFoiaFollowUpGmailSearchHints(self):
        """Test FoiaFollowUpGmailSearchHints"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
