# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.get_lad_filter_options200_response_position_types_inner import (
    GetLadFilterOptions200ResponsePositionTypesInner,
)


class TestGetLadFilterOptions200ResponsePositionTypesInner(unittest.TestCase):
    """GetLadFilterOptions200ResponsePositionTypesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GetLadFilterOptions200ResponsePositionTypesInner:
        """Test GetLadFilterOptions200ResponsePositionTypesInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetLadFilterOptions200ResponsePositionTypesInner`
        """
        model = GetLadFilterOptions200ResponsePositionTypesInner()
        if include_optional:
            return GetLadFilterOptions200ResponsePositionTypesInner(
                id = 1,
                name = 'Athletic Director',
                category = 'Senior Leadership'
            )
        else:
            return GetLadFilterOptions200ResponsePositionTypesInner(
        )
        """

    def testGetLadFilterOptions200ResponsePositionTypesInner(self):
        """Test GetLadFilterOptions200ResponsePositionTypesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
