# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.73-dev.10297
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.desk_admin_report_request import (
    DeskAdminReportRequest,
)


class TestDeskAdminReportRequest(unittest.TestCase):
    """DeskAdminReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeskAdminReportRequest:
        """Test DeskAdminReportRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeskAdminReportRequest`
        """
        model = DeskAdminReportRequest()
        if include_optional:
            return DeskAdminReportRequest(
                uuid = '',
                status = 'new',
                requester_name = '',
                body = '',
                category = 'coaches-staff',
                cta_key = 'another-sport',
                source_report_title = '',
                received_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                clock_paused = True
            )
        else:
            return DeskAdminReportRequest(
                uuid = '',
                status = 'new',
                requester_name = '',
                body = '',
                category = 'coaches-staff',
                cta_key = 'another-sport',
                source_report_title = '',
                received_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                clock_paused = True,
        )
        """

    def testDeskAdminReportRequest(self):
        """Test DeskAdminReportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
