# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.56-dev.10080
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.department_coach_verdict import (
    DepartmentCoachVerdict,
)


class TestDepartmentCoachVerdict(unittest.TestCase):
    """DepartmentCoachVerdict unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepartmentCoachVerdict:
        """Test DepartmentCoachVerdict
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DepartmentCoachVerdict`
        """
        model = DepartmentCoachVerdict()
        if include_optional:
            return DepartmentCoachVerdict(
                bucket = 'champion',
                pay_rank = 56,
                finish_rank = 56,
                delta = 56,
                first_year = True,
                contract_year = 56,
                contract_length_years = 56,
                approximate = True
            )
        else:
            return DepartmentCoachVerdict(
                bucket = 'champion',
                pay_rank = 56,
                finish_rank = 56,
                delta = 56,
                first_year = True,
                contract_year = 56,
                contract_length_years = 56,
                approximate = True,
        )
        """

    def testDepartmentCoachVerdict(self):
        """Test DepartmentCoachVerdict"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
