# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.8-dev.10620
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.desk_report_activity import DeskReportActivity


class TestDeskReportActivity(unittest.TestCase):
    """DeskReportActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeskReportActivity:
        """Test DeskReportActivity
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeskReportActivity`
        """
        model = DeskReportActivity()
        if include_optional:
            return DeskReportActivity(
                meta = None,
                data = [
                    winthrop_client_python.models.desk_activity_viewer.DeskActivityViewer(
                        user_id = '68072888001528021798096225500', 
                        name = '', 
                        email = '', 
                        status = 'active', 
                        current_access = True, 
                        opens = 1, 
                        first_viewed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_viewed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                summary = winthrop_client_python.models.desk_activity_summary.DeskActivitySummary(
                    unique_viewers = 0, 
                    total_opens = 0, ),
                period_totals = winthrop_client_python.models.desk_activity_summary.DeskActivitySummary(
                    unique_viewers = 0, 
                    total_opens = 0, ),
                error = winthrop_client_python.models.desk_report_activity_error.DeskReportActivity_error(
                    code = 'account_missing', 
                    message = '', )
            )
        else:
            return DeskReportActivity(
                meta = None,
                data = [
                    winthrop_client_python.models.desk_activity_viewer.DeskActivityViewer(
                        user_id = '68072888001528021798096225500', 
                        name = '', 
                        email = '', 
                        status = 'active', 
                        current_access = True, 
                        opens = 1, 
                        first_viewed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_viewed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                summary = winthrop_client_python.models.desk_activity_summary.DeskActivitySummary(
                    unique_viewers = 0, 
                    total_opens = 0, ),
                period_totals = winthrop_client_python.models.desk_activity_summary.DeskActivitySummary(
                    unique_viewers = 0, 
                    total_opens = 0, ),
                error = winthrop_client_python.models.desk_report_activity_error.DeskReportActivity_error(
                    code = 'account_missing', 
                    message = '', ),
        )
        """

    def testDeskReportActivity(self):
        """Test DeskReportActivity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
