# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.coach_compensation_tab_quartiles_rows_inner import (
    CoachCompensationTabQuartilesRowsInner,
)


class TestCoachCompensationTabQuartilesRowsInner(unittest.TestCase):
    """CoachCompensationTabQuartilesRowsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoachCompensationTabQuartilesRowsInner:
        """Test CoachCompensationTabQuartilesRowsInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CoachCompensationTabQuartilesRowsInner`
        """
        model = CoachCompensationTabQuartilesRowsInner()
        if include_optional:
            return CoachCompensationTabQuartilesRowsInner(
                group = '',
                percent_rank = 56,
                q25_cents = 56,
                q50_cents = 56,
                q75_cents = 56,
                q100_cents = 56
            )
        else:
            return CoachCompensationTabQuartilesRowsInner(
                q25_cents = 56,
                q50_cents = 56,
                q75_cents = 56,
                q100_cents = 56,
        )
        """

    def testCoachCompensationTabQuartilesRowsInner(self):
        """Test CoachCompensationTabQuartilesRowsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
