# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.57
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.athletic_profile_show_sport_overview_pay_ladder_inner import (
    AthleticProfileShowSportOverviewPayLadderInner,
)


class TestAthleticProfileShowSportOverviewPayLadderInner(unittest.TestCase):
    """AthleticProfileShowSportOverviewPayLadderInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> AthleticProfileShowSportOverviewPayLadderInner:
        """Test AthleticProfileShowSportOverviewPayLadderInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AthleticProfileShowSportOverviewPayLadderInner`
        """
        model = AthleticProfileShowSportOverviewPayLadderInner()
        if include_optional:
            return AthleticProfileShowSportOverviewPayLadderInner(
                coach_name = '',
                school_short_name = '',
                comp_cents = 56,
                is_subject = True
            )
        else:
            return AthleticProfileShowSportOverviewPayLadderInner(
        )
        """

    def testAthleticProfileShowSportOverviewPayLadderInner(self):
        """Test AthleticProfileShowSportOverviewPayLadderInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
