# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.30864390916
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.foia_inbox_add_cc_effect import FoiaInboxAddCcEffect


class TestFoiaInboxAddCcEffect(unittest.TestCase):
    """FoiaInboxAddCcEffect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoiaInboxAddCcEffect:
        """Test FoiaInboxAddCcEffect
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FoiaInboxAddCcEffect`
        """
        model = FoiaInboxAddCcEffect()
        if include_optional:
            return FoiaInboxAddCcEffect(
                action = 'add_cc',
                idempotency_key = 'gB:9JLe6iL71-aa-.Ctq01234567',
                expected_collection_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b',
                contact = winthrop_client_python.models.foia_inbox_contact_input.FoiaInboxContactInput(
                    first_name = '0', 
                    last_name = '0', 
                    email = '', 
                    position = '', 
                    phone = '', 
                    mailing_address = '', 
                    contact_page_url = '', )
            )
        else:
            return FoiaInboxAddCcEffect(
                action = 'add_cc',
                idempotency_key = 'gB:9JLe6iL71-aa-.Ctq01234567',
                expected_collection_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b',
                contact = winthrop_client_python.models.foia_inbox_contact_input.FoiaInboxContactInput(
                    first_name = '0', 
                    last_name = '0', 
                    email = '', 
                    position = '', 
                    phone = '', 
                    mailing_address = '', 
                    contact_page_url = '', ),
        )
        """

    def testFoiaInboxAddCcEffect(self):
        """Test FoiaInboxAddCcEffect"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
