# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.8
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.gad_school_summary import GadSchoolSummary


class TestGadSchoolSummary(unittest.TestCase):
    """GadSchoolSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GadSchoolSummary:
        """Test GadSchoolSummary
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GadSchoolSummary`
        """
        model = GadSchoolSummary()
        if include_optional:
            return GadSchoolSummary(
                school = winthrop_client_python.models.gad_school_summary_school.GadSchoolSummary_school(
                    id = 56, 
                    name = '', 
                    short_name = '', ),
                sport = winthrop_client_python.models.gad_school_summary_sport.GadSchoolSummary_sport(
                    id = 56, 
                    name = '', ),
                season_window = '',
                included_seasons = [
                    56
                    ],
                median_paid_out_cents = 56,
                median_received_cents = 56,
                mean_paid_out_cents = 56,
                mean_received_cents = 56,
                min_paid_out_cents = 56,
                max_paid_out_cents = 56,
                min_received_cents = 56,
                max_received_cents = 56,
                total_paid_out_cents = 56,
                total_received_cents = 56,
                paid_out_agreement_count = 56,
                received_agreement_count = 56,
                permission_filtered_count = 56,
                source_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                caveats = [
                    ''
                    ]
            )
        else:
            return GadSchoolSummary(
        )
        """

    def testGadSchoolSummary(self):
        """Test GadSchoolSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
