# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.25
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.foia_follow_up_requested_item import (
    FoiaFollowUpRequestedItem,
)


class TestFoiaFollowUpRequestedItem(unittest.TestCase):
    """FoiaFollowUpRequestedItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoiaFollowUpRequestedItem:
        """Test FoiaFollowUpRequestedItem
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FoiaFollowUpRequestedItem`
        """
        model = FoiaFollowUpRequestedItem()
        if include_optional:
            return FoiaFollowUpRequestedItem(
                requested_item_id = 56,
                requestable_type = '',
                requestable_id = 56,
                requestable_data = winthrop_client_python.models.foia_follow_up_requestable_data.FoiaFollowUpRequestableData(
                    id = 56, 
                    type = '', 
                    title = '', ),
                type_display = '',
                title = '',
                status = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                previous_status = '',
                received_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                coach_id = 56,
                coach_name = '',
                ri_note_id = 56,
                note = '',
                note_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FoiaFollowUpRequestedItem(
        )
        """

    def testFoiaFollowUpRequestedItem(self):
        """Test FoiaFollowUpRequestedItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
