# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.39-dev.10124
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.compensation_comparison_resolved_scope_conference import (
    CompensationComparisonResolvedScopeConference,
)


class TestCompensationComparisonResolvedScopeConference(unittest.TestCase):
    """CompensationComparisonResolvedScopeConference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> CompensationComparisonResolvedScopeConference:
        """Test CompensationComparisonResolvedScopeConference
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CompensationComparisonResolvedScopeConference`
        """
        model = CompensationComparisonResolvedScopeConference()
        if include_optional:
            return CompensationComparisonResolvedScopeConference(
                id = 56,
                name = ''
            )
        else:
            return CompensationComparisonResolvedScopeConference(
        )
        """

    def testCompensationComparisonResolvedScopeConference(self):
        """Test CompensationComparisonResolvedScopeConference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
