# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.56
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.athletic_profile_show_sport_coach_staff_staff_pool import (
    AthleticProfileShowSportCoachStaffStaffPool,
)


class TestAthleticProfileShowSportCoachStaffStaffPool(unittest.TestCase):
    """AthleticProfileShowSportCoachStaffStaffPool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> AthleticProfileShowSportCoachStaffStaffPool:
        """Test AthleticProfileShowSportCoachStaffStaffPool
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AthleticProfileShowSportCoachStaffStaffPool`
        """
        model = AthleticProfileShowSportCoachStaffStaffPool()
        if include_optional:
            return AthleticProfileShowSportCoachStaffStaffPool(
                pool_cents = 56,
                cohort_size = 56,
                cohort_rank = 56,
                median_cents = 56
            )
        else:
            return AthleticProfileShowSportCoachStaffStaffPool(
        )
        """

    def testAthleticProfileShowSportCoachStaffStaffPool(self):
        """Test AthleticProfileShowSportCoachStaffStaffPool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
