# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.53-dev.10206
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.school_department_guarantees import (
    SchoolDepartmentGuarantees,
)


class TestSchoolDepartmentGuarantees(unittest.TestCase):
    """SchoolDepartmentGuarantees unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchoolDepartmentGuarantees:
        """Test SchoolDepartmentGuarantees
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SchoolDepartmentGuarantees`
        """
        model = SchoolDepartmentGuarantees()
        if include_optional:
            return SchoolDepartmentGuarantees(
                school = winthrop_client_python.models.school_department_guarantees_school.SchoolDepartmentGuarantees_school(
                    id = 56, 
                    name = '', 
                    short_name = '', 
                    private = True, ),
                conference = winthrop_client_python.models.school_department_overview_conference.SchoolDepartmentOverview_conference(
                    id = 56, 
                    name = '', ),
                season_year = 56,
                latest_filed_year = 56,
                selected_year = 56,
                available_years = [
                    56
                    ],
                quadrant = winthrop_client_python.models.department_guarantees_quadrant.DepartmentGuaranteesQuadrant(
                    cohort_size = 56, 
                    points = [
                        winthrop_client_python.models.department_guarantees_quadrant_point.DepartmentGuaranteesQuadrantPoint(
                            school_id = 56, 
                            name = '', 
                            is_subject = True, 
                            colors = '', 
                            paid_cents = 56, 
                            received_cents = 56, )
                        ], 
                    unplotted = [
                        winthrop_client_python.models.department_financials_unplotted_school.DepartmentFinancialsUnplottedSchool(
                            school_id = 56, 
                            name = '', 
                            reason = 'private', )
                        ], ),
                filed_line = winthrop_client_python.models.department_guarantees_filed_line.DepartmentGuaranteesFiledLine(
                    year = 56, 
                    expense_cents = 56, 
                    revenue_cents = 56, ),
                committed_out = winthrop_client_python.models.department_guarantees_committed_side.DepartmentGuaranteesCommittedSide(
                    total_cents = 56, 
                    count = 56, 
                    tbd_count = 56, ),
                committed_in = winthrop_client_python.models.department_guarantees_committed_side.DepartmentGuaranteesCommittedSide(
                    total_cents = 56, 
                    count = 56, 
                    tbd_count = 56, ),
                sports = [
                    winthrop_client_python.models.department_guarantees_sport_ledger.DepartmentGuaranteesSportLedger(
                        sport_id = 56, 
                        sport_key = '', 
                        sport_name = '', 
                        agreement_count = 56, 
                        out_count = 56, 
                        out_total_cents = 56, 
                        out_median_cents = 56, 
                        agreements = [
                            winthrop_client_python.models.department_guarantees_agreement.DepartmentGuaranteesAgreement(
                                game_contract_id = 56, 
                                direction = 'out', 
                                opponent = winthrop_client_python.models.department_guarantees_agreement_opponent.DepartmentGuaranteesAgreement_opponent(
                                    school_id = 56, 
                                    name = '', ), 
                                game_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                game_date_tbd = '', 
                                comp_cents = 56, 
                                comp_tbd = True, 
                                has_document = True, 
                                belongs_to_series = True, )
                            ], )
                    ],
                market = winthrop_client_python.models.department_guarantees_market.DepartmentGuaranteesMarket(
                    window = '', 
                    seasons = [
                        56
                        ], 
                    football = winthrop_client_python.models.department_guarantees_market_side.DepartmentGuaranteesMarketSide(
                        your_median_cents = 56, 
                        market_median_cents = 56, 
                        market_count = 56, ), 
                    mens_basketball = winthrop_client_python.models.department_guarantees_market_side.DepartmentGuaranteesMarketSide(
                        your_median_cents = 56, 
                        market_median_cents = 56, 
                        market_count = 56, ), ),
                trend = [
                    winthrop_client_python.models.department_guarantees_trend_entry.DepartmentGuaranteesTrendEntry(
                        season_year = 56, 
                        out_total_cents = 56, 
                        out_count = 56, 
                        provisional = True, )
                    ]
            )
        else:
            return SchoolDepartmentGuarantees(
                school = winthrop_client_python.models.school_department_guarantees_school.SchoolDepartmentGuarantees_school(
                    id = 56, 
                    name = '', 
                    short_name = '', 
                    private = True, ),
                conference = winthrop_client_python.models.school_department_overview_conference.SchoolDepartmentOverview_conference(
                    id = 56, 
                    name = '', ),
                season_year = 56,
                latest_filed_year = 56,
                selected_year = 56,
                available_years = [
                    56
                    ],
                quadrant = winthrop_client_python.models.department_guarantees_quadrant.DepartmentGuaranteesQuadrant(
                    cohort_size = 56, 
                    points = [
                        winthrop_client_python.models.department_guarantees_quadrant_point.DepartmentGuaranteesQuadrantPoint(
                            school_id = 56, 
                            name = '', 
                            is_subject = True, 
                            colors = '', 
                            paid_cents = 56, 
                            received_cents = 56, )
                        ], 
                    unplotted = [
                        winthrop_client_python.models.department_financials_unplotted_school.DepartmentFinancialsUnplottedSchool(
                            school_id = 56, 
                            name = '', 
                            reason = 'private', )
                        ], ),
                filed_line = winthrop_client_python.models.department_guarantees_filed_line.DepartmentGuaranteesFiledLine(
                    year = 56, 
                    expense_cents = 56, 
                    revenue_cents = 56, ),
                committed_out = winthrop_client_python.models.department_guarantees_committed_side.DepartmentGuaranteesCommittedSide(
                    total_cents = 56, 
                    count = 56, 
                    tbd_count = 56, ),
                committed_in = winthrop_client_python.models.department_guarantees_committed_side.DepartmentGuaranteesCommittedSide(
                    total_cents = 56, 
                    count = 56, 
                    tbd_count = 56, ),
                sports = [
                    winthrop_client_python.models.department_guarantees_sport_ledger.DepartmentGuaranteesSportLedger(
                        sport_id = 56, 
                        sport_key = '', 
                        sport_name = '', 
                        agreement_count = 56, 
                        out_count = 56, 
                        out_total_cents = 56, 
                        out_median_cents = 56, 
                        agreements = [
                            winthrop_client_python.models.department_guarantees_agreement.DepartmentGuaranteesAgreement(
                                game_contract_id = 56, 
                                direction = 'out', 
                                opponent = winthrop_client_python.models.department_guarantees_agreement_opponent.DepartmentGuaranteesAgreement_opponent(
                                    school_id = 56, 
                                    name = '', ), 
                                game_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                game_date_tbd = '', 
                                comp_cents = 56, 
                                comp_tbd = True, 
                                has_document = True, 
                                belongs_to_series = True, )
                            ], )
                    ],
                market = winthrop_client_python.models.department_guarantees_market.DepartmentGuaranteesMarket(
                    window = '', 
                    seasons = [
                        56
                        ], 
                    football = winthrop_client_python.models.department_guarantees_market_side.DepartmentGuaranteesMarketSide(
                        your_median_cents = 56, 
                        market_median_cents = 56, 
                        market_count = 56, ), 
                    mens_basketball = winthrop_client_python.models.department_guarantees_market_side.DepartmentGuaranteesMarketSide(
                        your_median_cents = 56, 
                        market_median_cents = 56, 
                        market_count = 56, ), ),
                trend = [
                    winthrop_client_python.models.department_guarantees_trend_entry.DepartmentGuaranteesTrendEntry(
                        season_year = 56, 
                        out_total_cents = 56, 
                        out_count = 56, 
                        provisional = True, )
                    ],
        )
        """

    def testSchoolDepartmentGuarantees(self):
        """Test SchoolDepartmentGuarantees"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
