# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.update_deal_request_deal_detail import (
    UpdateDealRequestDealDetail,
)


class TestUpdateDealRequestDealDetail(unittest.TestCase):
    """UpdateDealRequestDealDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateDealRequestDealDetail:
        """Test UpdateDealRequestDealDetail
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UpdateDealRequestDealDetail`
        """
        model = UpdateDealRequestDealDetail()
        if include_optional:
            return UpdateDealRequestDealDetail(
                cash_annual_avg = None,
                prod_allot_annual_avg = None,
                min_purchase_obl = None,
                signing_bonus = None,
                contingent_bonus = True,
                sports = [
                    null
                    ],
                grf = None,
                bha = None,
                additional_rev = None,
                rev_share_percent = None
            )
        else:
            return UpdateDealRequestDealDetail(
        )
        """

    def testUpdateDealRequestDealDetail(self):
        """Test UpdateDealRequestDealDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
