# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.team_schedule_detail import TeamScheduleDetail


class TestTeamScheduleDetail(unittest.TestCase):
    """TeamScheduleDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamScheduleDetail:
        """Test TeamScheduleDetail
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TeamScheduleDetail`
        """
        model = TeamScheduleDetail()
        if include_optional:
            return TeamScheduleDetail(
                school = winthrop_client_python.models.team_schedule_detail_school.TeamScheduleDetail_school(
                    id = 56, 
                    name = '', 
                    logo_url = '', 
                    city = '', 
                    state_name = '', 
                    conference_name = '', ),
                sport = winthrop_client_python.models.contact_search_coach_options_sports_inner.ContactSearchCoachOptions_sports_inner(
                    id = 56, 
                    name = '', 
                    name_display = '', ),
                season_year = 56,
                performance_year = 56,
                season = winthrop_client_python.models.team_schedule_detail_season.TeamScheduleDetail_season(
                    wins = 56, 
                    losses = 56, 
                    record_str = '', 
                    rpi = 56, 
                    avg_rpi = 56, ),
                head_coach = winthrop_client_python.models.team_schedule_detail_head_coach.TeamScheduleDetail_head_coach(
                    id = 56, 
                    name = '', 
                    photo_url = '', ),
                non_conf_games_count = 56,
                fil_team_id = '',
                available_years = [
                    56
                    ],
                contacts = [
                    winthrop_client_python.models.team_schedule_contact.TeamScheduleContact(
                        coach_id = 56, 
                        name = '', 
                        title = '', 
                        email = '', 
                        phone = '', 
                        avatar_url = '', )
                    ],
                games = [
                    winthrop_client_python.models.team_schedule_detail_game.TeamScheduleDetailGame(
                        id = 56, 
                        game_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        game_date_display = '', 
                        opponent_id = 56, 
                        opponent_name = '', 
                        location = 'Home', 
                        city = '', 
                        state_name = '', 
                        opponent_rpi = 56, 
                        opponent_avg_rpi = 56, 
                        result = 'W', 
                        score = '', 
                        overtime = 56, 
                        in_conference = True, )
                    ]
            )
        else:
            return TeamScheduleDetail(
        )
        """

    def testTeamScheduleDetail(self):
        """Test TeamScheduleDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
