# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.create_game_post_search_request import (
    CreateGamePostSearchRequest,
)


class TestCreateGamePostSearchRequest(unittest.TestCase):
    """CreateGamePostSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateGamePostSearchRequest:
        """Test CreateGamePostSearchRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateGamePostSearchRequest`
        """
        model = CreateGamePostSearchRequest()
        if include_optional:
            return CreateGamePostSearchRequest(
                game_post = winthrop_client_python.models.create_game_post_search_request_game_post.create_game_post_search_request_game_post(
                    sport_id = 56, 
                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    description = '', 
                    game_type_ids = [
                        56
                        ], )
            )
        else:
            return CreateGamePostSearchRequest(
                game_post = winthrop_client_python.models.create_game_post_search_request_game_post.create_game_post_search_request_game_post(
                    sport_id = 56, 
                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    description = '', 
                    game_type_ids = [
                        56
                        ], ),
        )
        """

    def testCreateGamePostSearchRequest(self):
        """Test CreateGamePostSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
