# coding: utf-8

"""
    Winthrop Intelligence Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.20.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from winthrop_client_python.models.average_compensation import AverageCompensation


class TestAverageCompensation(unittest.TestCase):
    """AverageCompensation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AverageCompensation:
        """Test AverageCompensation
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AverageCompensation`
        """
        model = AverageCompensation()
        if include_optional:
            return AverageCompensation(
                mean = 1.337,
                median = 1.337,
                mode = 1.337,
                min = 1.337,
                max = 1.337
            )
        else:
            return AverageCompensation(
        )
        """

    def testAverageCompensation(self):
        """Test AverageCompensation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
