# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.47.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.create_schedule_intent_request_schedule_intent import (
    CreateScheduleIntentRequestScheduleIntent,
)


class TestCreateScheduleIntentRequestScheduleIntent(unittest.TestCase):
    """CreateScheduleIntentRequestScheduleIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> CreateScheduleIntentRequestScheduleIntent:
        """Test CreateScheduleIntentRequestScheduleIntent
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateScheduleIntentRequestScheduleIntent`
        """
        model = CreateScheduleIntentRequestScheduleIntent()
        if include_optional:
            return CreateScheduleIntentRequestScheduleIntent(
                sport_id = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                game_type_ids = [
                    56
                    ]
            )
        else:
            return CreateScheduleIntentRequestScheduleIntent(
                sport_id = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testCreateScheduleIntentRequestScheduleIntent(self):
        """Test CreateScheduleIntentRequestScheduleIntent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
