# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.70-dev.10297
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.desk_report_summary_cover import (
    DeskReportSummaryCover,
)


class TestDeskReportSummaryCover(unittest.TestCase):
    """DeskReportSummaryCover unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeskReportSummaryCover:
        """Test DeskReportSummaryCover
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeskReportSummaryCover`
        """
        model = DeskReportSummaryCover()
        if include_optional:
            return DeskReportSummaryCover(
                treatment = 'ink',
                kicker = '',
                numeral = ''
            )
        else:
            return DeskReportSummaryCover(
                treatment = 'ink',
                kicker = '',
                numeral = '',
        )
        """

    def testDeskReportSummaryCover(self):
        """Test DeskReportSummaryCover"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
