# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.desk_admin_errors_response import (
    DeskAdminErrorsResponse,
)


class TestDeskAdminErrorsResponse(unittest.TestCase):
    """DeskAdminErrorsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeskAdminErrorsResponse:
        """Test DeskAdminErrorsResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeskAdminErrorsResponse`
        """
        model = DeskAdminErrorsResponse()
        if include_optional:
            return DeskAdminErrorsResponse(
                errors = [
                    null
                    ]
            )
        else:
            return DeskAdminErrorsResponse(
                errors = [
                    null
                    ],
        )
        """

    def testDeskAdminErrorsResponse(self):
        """Test DeskAdminErrorsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
