# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.snapshot_income_report import SnapshotIncomeReport


class TestSnapshotIncomeReport(unittest.TestCase):
    """SnapshotIncomeReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnapshotIncomeReport:
        """Test SnapshotIncomeReport
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SnapshotIncomeReport`
        """
        model = SnapshotIncomeReport()
        if include_optional:
            return SnapshotIncomeReport(
                id = 56,
                year = 56,
                raw_contract_id = 56
            )
        else:
            return SnapshotIncomeReport(
                id = 56,
                year = 56,
        )
        """

    def testSnapshotIncomeReport(self):
        """Test SnapshotIncomeReport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
