# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.game_post_detail_created_by import (
    GamePostDetailCreatedBy,
)


class TestGamePostDetailCreatedBy(unittest.TestCase):
    """GamePostDetailCreatedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GamePostDetailCreatedBy:
        """Test GamePostDetailCreatedBy
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GamePostDetailCreatedBy`
        """
        model = GamePostDetailCreatedBy()
        if include_optional:
            return GamePostDetailCreatedBy(
                name = '',
                coach_id = 56
            )
        else:
            return GamePostDetailCreatedBy(
        )
        """

    def testGamePostDetailCreatedBy(self):
        """Test GamePostDetailCreatedBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
