# coding: utf-8

"""
    Winthrop Intelligence Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from winthrop_client_python.models.position_type_group import PositionTypeGroup


class TestPositionTypeGroup(unittest.TestCase):
    """PositionTypeGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PositionTypeGroup:
        """Test PositionTypeGroup
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PositionTypeGroup`
        """
        model = PositionTypeGroup()
        if include_optional:
            return PositionTypeGroup(
                id = 1,
                name = 'POSITION TYPE GROUP NAME',
                name_display = 'Position Type Group Name',
                ord = 2,
                created_at = '2019-01-01T00:00Z',
                updated_at = '2019-01-01T00:00Z'
            )
        else:
            return PositionTypeGroup(
        )
        """

    def testPositionTypeGroup(self):
        """Test PositionTypeGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
