# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.70-dev.10297
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.desk_report_full import DeskReportFull


class TestDeskReportFull(unittest.TestCase):
    """DeskReportFull unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeskReportFull:
        """Test DeskReportFull
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeskReportFull`
        """
        model = DeskReportFull()
        if include_optional:
            return DeskReportFull(
                uuid = '',
                title = '',
                category = 'Financials',
                report_type = 'intelligence_brief',
                summary = '',
                headline_stats = [
                    winthrop_client_python.models.desk_headline_stat.DeskHeadlineStat(
                        value = '', 
                        label = '', )
                    ],
                cover = winthrop_client_python.models.desk_report_summary_cover.DeskReportSummary_cover(
                    treatment = 'ink', 
                    kicker = '', 
                    numeral = '', ),
                published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                page_count = 56,
                artifact_kinds = [
                    'pdf'
                    ],
                artifacts = [
                    winthrop_client_python.models.desk_report_artifact.DeskReportArtifact(
                        kind = 'pdf', 
                        filename = '', 
                        url = '', )
                    ],
                rerun_cadence = 'false',
                push_example = '',
                unread = True,
                request_context = winthrop_client_python.models.desk_request_context.DeskRequestContext(
                    request_uuid = '', 
                    requester_name = '', 
                    requested_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    quote = '', 
                    delivered_in_label = '', ),
                body_html = '',
                sections = [
                    winthrop_client_python.models.desk_report_full_all_of_sections.DeskReportFull_allOf_sections(
                        id = '', 
                        title = '', 
                        index = 56, )
                    ],
                version_number = 56,
                first_open = True
            )
        else:
            return DeskReportFull(
                uuid = '',
                title = '',
                category = 'Financials',
                report_type = 'intelligence_brief',
                summary = '',
                headline_stats = [
                    winthrop_client_python.models.desk_headline_stat.DeskHeadlineStat(
                        value = '', 
                        label = '', )
                    ],
                cover = winthrop_client_python.models.desk_report_summary_cover.DeskReportSummary_cover(
                    treatment = 'ink', 
                    kicker = '', 
                    numeral = '', ),
                published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                page_count = 56,
                artifact_kinds = [
                    'pdf'
                    ],
                artifacts = [
                    winthrop_client_python.models.desk_report_artifact.DeskReportArtifact(
                        kind = 'pdf', 
                        filename = '', 
                        url = '', )
                    ],
                rerun_cadence = 'false',
                push_example = '',
                unread = True,
                request_context = winthrop_client_python.models.desk_request_context.DeskRequestContext(
                    request_uuid = '', 
                    requester_name = '', 
                    requested_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    quote = '', 
                    delivered_in_label = '', ),
                body_html = '',
                sections = [
                    winthrop_client_python.models.desk_report_full_all_of_sections.DeskReportFull_allOf_sections(
                        id = '', 
                        title = '', 
                        index = 56, )
                    ],
                version_number = 56,
                first_open = True,
        )
        """

    def testDeskReportFull(self):
        """Test DeskReportFull"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
