# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.21-dev.9985
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.requested_item_note_response import (
    RequestedItemNoteResponse,
)


class TestRequestedItemNoteResponse(unittest.TestCase):
    """RequestedItemNoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestedItemNoteResponse:
        """Test RequestedItemNoteResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RequestedItemNoteResponse`
        """
        model = RequestedItemNoteResponse()
        if include_optional:
            return RequestedItemNoteResponse(
                data = winthrop_client_python.models.requested_item_note.RequestedItemNote(
                    id = 1, 
                    requested_item_id = 2, 
                    note = 'Received employment contract.', 
                    user_id = 3, 
                    created_at = '2019-01-01T00:00Z', 
                    updated_at = '2019-01-01T00:00Z', )
            )
        else:
            return RequestedItemNoteResponse(
        )
        """

    def testRequestedItemNoteResponse(self):
        """Test RequestedItemNoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
