# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.team_schedule_coaches import TeamScheduleCoaches


class TestTeamScheduleCoaches(unittest.TestCase):
    """TeamScheduleCoaches unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamScheduleCoaches:
        """Test TeamScheduleCoaches
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TeamScheduleCoaches`
        """
        model = TeamScheduleCoaches()
        if include_optional:
            return TeamScheduleCoaches(
                performance_year = 56,
                performance_years = [
                    56
                    ],
                sport_name = '',
                coaches = [
                    winthrop_client_python.models.team_schedule_coaches_coaches_inner.TeamScheduleCoaches_coaches_inner(
                        id = 56, 
                        name = '', 
                        title = '', 
                        email = '', 
                        phone = '', 
                        photo_url = '', 
                        compensation = '', 
                        compensation_cents = 56, )
                    ],
                head_coaches = [
                    [
                        winthrop_client_python.models.team_schedule_coaches_head_coaches_inner_inner.TeamScheduleCoaches_head_coaches_inner_inner(
                            id = 56, 
                            name = '', 
                            photo_url = '', )
                        ]
                    ],
                seasons = [
                    winthrop_client_python.models.team_schedule_coaches_seasons_inner.TeamScheduleCoaches_seasons_inner(
                        year = 56, 
                        wins = 56, 
                        losses = 56, 
                        ties = 56, 
                        rpi = 56, 
                        record_str = '', 
                        conference_record = '', 
                        postseason = '', 
                        home_record = '', 
                        home_win_percent = 1.337, 
                        sos_ranking = 56, 
                        offensive_efficiency = 1.337, 
                        defensive_efficiency = 1.337, )
                    ]
            )
        else:
            return TeamScheduleCoaches(
        )
        """

    def testTeamScheduleCoaches(self):
        """Test TeamScheduleCoaches"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
