# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.38.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from winthrop_client_python.models.get_school_alternate_names404_response import (
    GetSchoolAlternateNames404Response,
)


class TestGetSchoolAlternateNames404Response(unittest.TestCase):
    """GetSchoolAlternateNames404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSchoolAlternateNames404Response:
        """Test GetSchoolAlternateNames404Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetSchoolAlternateNames404Response`
        """
        model = GetSchoolAlternateNames404Response()
        if include_optional:
            return GetSchoolAlternateNames404Response(
                error = 'School not found'
            )
        else:
            return GetSchoolAlternateNames404Response(
        )
        """

    def testGetSchoolAlternateNames404Response(self):
        """Test GetSchoolAlternateNames404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
