# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.30063844626
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.foia_inbox_processing_event_response import (
    FoiaInboxProcessingEventResponse,
)


class TestFoiaInboxProcessingEventResponse(unittest.TestCase):
    """FoiaInboxProcessingEventResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoiaInboxProcessingEventResponse:
        """Test FoiaInboxProcessingEventResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FoiaInboxProcessingEventResponse`
        """
        model = FoiaInboxProcessingEventResponse()
        if include_optional:
            return FoiaInboxProcessingEventResponse(
                id = 56,
                mailbox = '',
                gmail_message_id = '',
                gmail_thread_id = '',
                run_id = '',
                foia_request_id = 56,
                school_id = 56,
                decision_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b',
                request_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b',
                status = '',
                applied_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                result = { },
                idempotent = True
            )
        else:
            return FoiaInboxProcessingEventResponse(
        )
        """

    def testFoiaInboxProcessingEventResponse(self):
        """Test FoiaInboxProcessingEventResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
