# coding: utf-8

"""
    Winthrop Intelligence Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import winthrop_client_python
from winthrop_client_python.models.job_post import JobPost  # noqa: E501
from winthrop_client_python.rest import ApiException


class TestJobPost(unittest.TestCase):
    """JobPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JobPost
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `JobPost`
        """
        model = winthrop_client_python.models.job_post.JobPost()  # noqa: E501
        if include_optional :
            return JobPost(
                id = 56, 
                title = '', 
                department = '', 
                link = '', 
                uid = '', 
                work_type = '', 
                description = '', 
                school_id = 56, 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return JobPost(
                uid = '',
                description = '',
                school_id = 56,
        )
        """

    def testJobPost(self):
        """Test JobPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
