# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.create_contact_search_request import (
    CreateContactSearchRequest,
)


class TestCreateContactSearchRequest(unittest.TestCase):
    """CreateContactSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateContactSearchRequest:
        """Test CreateContactSearchRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateContactSearchRequest`
        """
        model = CreateContactSearchRequest()
        if include_optional:
            return CreateContactSearchRequest(
                contact = winthrop_client_python.models.create_contact_search_request_contact.create_contact_search_request_contact(
                    coach_id = 56, 
                    school_id = 56, 
                    sport_id = 56, )
            )
        else:
            return CreateContactSearchRequest(
        )
        """

    def testCreateContactSearchRequest(self):
        """Test CreateContactSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
