# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.update_password_reset400_response import (
    UpdatePasswordReset400Response,
)


class TestUpdatePasswordReset400Response(unittest.TestCase):
    """UpdatePasswordReset400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdatePasswordReset400Response:
        """Test UpdatePasswordReset400Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UpdatePasswordReset400Response`
        """
        model = UpdatePasswordReset400Response()
        if include_optional:
            return UpdatePasswordReset400Response(
                errors = [
                    ''
                    ]
            )
        else:
            return UpdatePasswordReset400Response(
        )
        """

    def testUpdatePasswordReset400Response(self):
        """Test UpdatePasswordReset400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
