# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.17
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.create_page_view_request import CreatePageViewRequest


class TestCreatePageViewRequest(unittest.TestCase):
    """CreatePageViewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePageViewRequest:
        """Test CreatePageViewRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreatePageViewRequest`
        """
        model = CreatePageViewRequest()
        if include_optional:
            return CreatePageViewRequest(
                route = '',
                search = '',
                tab = ''
            )
        else:
            return CreatePageViewRequest(
                route = '',
        )
        """

    def testCreatePageViewRequest(self):
        """Test CreatePageViewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
