# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.2-dev.10366
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.desk_request_context import DeskRequestContext


class TestDeskRequestContext(unittest.TestCase):
    """DeskRequestContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeskRequestContext:
        """Test DeskRequestContext
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeskRequestContext`
        """
        model = DeskRequestContext()
        if include_optional:
            return DeskRequestContext(
                request_uuid = '',
                requester_name = '',
                requested_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                quote = '',
                delivered_in_label = ''
            )
        else:
            return DeskRequestContext(
                request_uuid = '',
                requester_name = '',
                requested_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                quote = '',
                delivered_in_label = '',
        )
        """

    def testDeskRequestContext(self):
        """Test DeskRequestContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
