# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.50
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.api.foia_inbox_api import FoiaInboxApi


class TestFoiaInboxApi(unittest.TestCase):
    """FoiaInboxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FoiaInboxApi()

    def tearDown(self) -> None:
        pass

    def test_apply_foia_inbox(self) -> None:
        """Test case for apply_foia_inbox"""
        pass

    def test_get_foia_inbox_candidates(self) -> None:
        """Test case for get_foia_inbox_candidates"""
        pass


if __name__ == "__main__":
    unittest.main()
