# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.7
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.income_report_input import IncomeReportInput


class TestIncomeReportInput(unittest.TestCase):
    """IncomeReportInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IncomeReportInput:
        """Test IncomeReportInput
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `IncomeReportInput`
        """
        model = IncomeReportInput()
        if include_optional:
            return IncomeReportInput(
                coach_id = 2,
                raw_contract_id = 3,
                year = 2011,
                notes = '',
                contract_status_id = 5,
                change_note = ''
            )
        else:
            return IncomeReportInput(
        )
        """

    def testIncomeReportInput(self):
        """Test IncomeReportInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
