# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.41.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from winthrop_client_python.models.user_request_collection import UserRequestCollection


class TestUserRequestCollection(unittest.TestCase):
    """UserRequestCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserRequestCollection:
        """Test UserRequestCollection
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserRequestCollection`
        """
        model = UserRequestCollection()
        if include_optional:
            return UserRequestCollection(
                data = [
                    winthrop_client_python.models.user_request.UserRequest(
                        id = 56, 
                        user_id = 56, 
                        url = '', 
                        ip_address = '', 
                        data1 = '', 
                        created_at = '2019-01-01T00:00Z', 
                        updated_at = '2019-01-01T00:00Z', 
                        request_type = 56, 
                        tab = '', 
                        city = '', 
                        state = '', 
                        latitude = 1.337, 
                        longitude = 1.337, 
                        device_id = 56, )
                    ],
                meta = winthrop_client_python.models.meta.Meta(
                    current_page = 2, 
                    total_pages = 7, 
                    total_entries = 654, 
                    next_page = 3, 
                    previous_page = 1, )
            )
        else:
            return UserRequestCollection(
        )
        """

    def testUserRequestCollection(self):
        """Test UserRequestCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
