# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.update_admin_desk_settings422_response import (
    UpdateAdminDeskSettings422Response,
)


class TestUpdateAdminDeskSettings422Response(unittest.TestCase):
    """UpdateAdminDeskSettings422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAdminDeskSettings422Response:
        """Test UpdateAdminDeskSettings422Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UpdateAdminDeskSettings422Response`
        """
        model = UpdateAdminDeskSettings422Response()
        if include_optional:
            return UpdateAdminDeskSettings422Response(
                errors = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return UpdateAdminDeskSettings422Response(
        )
        """

    def testUpdateAdminDeskSettings422Response(self):
        """Test UpdateAdminDeskSettings422Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
