# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.57
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.athletic_profile_show_sport_coach_staff import (
    AthleticProfileShowSportCoachStaff,
)


class TestAthleticProfileShowSportCoachStaff(unittest.TestCase):
    """AthleticProfileShowSportCoachStaff unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AthleticProfileShowSportCoachStaff:
        """Test AthleticProfileShowSportCoachStaff
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AthleticProfileShowSportCoachStaff`
        """
        model = AthleticProfileShowSportCoachStaff()
        if include_optional:
            return AthleticProfileShowSportCoachStaff(
                season_year = 56,
                conference_name = '',
                quadrant_points = [
                    winthrop_client_python.models.athletic_profile_show_sport_coach_staff_quadrant_points_inner.AthleticProfileShow_sport_coach_staff_quadrant_points_inner(
                        school_id = 56, 
                        name = '', 
                        short_name = '', 
                        colors = '', 
                        is_subject = True, 
                        coach_name = '', 
                        comp_cents = 56, 
                        net_rank = 56, 
                        net_year = 56, 
                        record = '', )
                    ],
                head_coach = winthrop_client_python.models.athletic_profile_show_sport_coach_staff_head_coach.AthleticProfileShow_sport_coach_staff_head_coach(
                    coach_id = 56, 
                    name = '', 
                    comp_cents = 56, 
                    base_salary_cents = 56, 
                    comp_rank = 56, 
                    comp_cohort_size = 56, 
                    comp_median_cents = 56, 
                    contract_start_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    contract_end_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    contract_on_file = True, 
                    at_will = True, 
                    interim = True, 
                    first_season_year = 56, 
                    career_season_count = 56, 
                    year_one = winthrop_client_python.models.athletic_profile_show_sport_coach_staff_head_coach_year_one.AthleticProfileShow_sport_coach_staff_head_coach_year_one(
                        year = 56, 
                        record = '', 
                        conference_record = '', 
                        net_rank = 56, ), 
                    career = [
                        winthrop_client_python.models.athletic_profile_show_sport_coach_staff_head_coach_career_inner.AthleticProfileShow_sport_coach_staff_head_coach_career_inner(
                            year = 56, 
                            school_short_name = '', 
                            record = '', 
                            net_rank = 56, 
                            postseason = '', 
                            is_subject_school = True, )
                        ], ),
                assistants = [
                    winthrop_client_python.models.athletic_profile_show_sport_coach_staff_assistants_inner.AthleticProfileShow_sport_coach_staff_assistants_inner(
                        coach_id = 56, 
                        name = '', 
                        title = '', 
                        comp_cents = 56, 
                        contract_end_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        at_will = True, 
                        on_file = True, )
                    ],
                staff_pool = winthrop_client_python.models.athletic_profile_show_sport_coach_staff_staff_pool.AthleticProfileShow_sport_coach_staff_staff_pool(
                    pool_cents = 56, 
                    cohort_size = 56, 
                    cohort_rank = 56, 
                    median_cents = 56, ),
                support_staff = [
                    winthrop_client_python.models.athletic_profile_show_sport_coach_staff_support_staff_inner.AthleticProfileShow_sport_coach_staff_support_staff_inner(
                        coach_id = 56, 
                        name = '', 
                        title = '', 
                        comp_cents = 56, 
                        on_file = True, )
                    ],
                as_of = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return AthleticProfileShowSportCoachStaff(
        )
        """

    def testAthleticProfileShowSportCoachStaff(self):
        """Test AthleticProfileShowSportCoachStaff"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
