# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.56-dev.10080
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.department_administrators990_officer import (
    DepartmentAdministrators990Officer,
)


class TestDepartmentAdministrators990Officer(unittest.TestCase):
    """DepartmentAdministrators990Officer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepartmentAdministrators990Officer:
        """Test DepartmentAdministrators990Officer
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DepartmentAdministrators990Officer`
        """
        model = DepartmentAdministrators990Officer()
        if include_optional:
            return DepartmentAdministrators990Officer(
                coach_id = 56,
                friendly_id = '',
                name = '',
                title = '',
                amount_cents = 56,
                fiscal_year = 56
            )
        else:
            return DepartmentAdministrators990Officer(
                coach_id = 56,
                friendly_id = '',
                name = '',
                title = '',
                amount_cents = 56,
                fiscal_year = 56,
        )
        """

    def testDepartmentAdministrators990Officer(self):
        """Test DepartmentAdministrators990Officer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
