# coding: utf-8

"""
    Winthrop Intelligence Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from winthrop_client_python.models.conferenceship_collection import (
    ConferenceshipCollection,
)


class TestConferenceshipCollection(unittest.TestCase):
    """ConferenceshipCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConferenceshipCollection:
        """Test ConferenceshipCollection
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ConferenceshipCollection`
        """
        model = ConferenceshipCollection()
        if include_optional:
            return ConferenceshipCollection(
                data = [
                    winthrop_client_python.models.conferenceship.Conferenceship(
                        id = 56, 
                        school_id = 56, 
                        sport_id = 56, 
                        conference_id = 56, 
                        created_at = '2019-01-01T00:00Z', 
                        updated_at = '2019-01-01T00:00Z', )
                    ],
                meta = winthrop_client_python.models.meta.Meta(
                    current_page = 2, 
                    total_pages = 7, 
                    total_entries = 654, 
                    next_page = 3, 
                    previous_page = 1, )
            )
        else:
            return ConferenceshipCollection(
        )
        """

    def testConferenceshipCollection(self):
        """Test ConferenceshipCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
