# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.30118092924
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.ctb_compensation_expected_request import (
    CtbCompensationExpectedRequest,
)


class TestCtbCompensationExpectedRequest(unittest.TestCase):
    """CtbCompensationExpectedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CtbCompensationExpectedRequest:
        """Test CtbCompensationExpectedRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CtbCompensationExpectedRequest`
        """
        model = CtbCompensationExpectedRequest()
        if include_optional:
            return CtbCompensationExpectedRequest(
                status = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by_school = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                updated_by_wi = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                foia_notes_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b'
            )
        else:
            return CtbCompensationExpectedRequest(
                status = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by_school = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                updated_by_wi = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                foia_notes_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b',
        )
        """

    def testCtbCompensationExpectedRequest(self):
        """Test CtbCompensationExpectedRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
