# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.30118092924
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.foia_inbox_candidates_meta import (
    FoiaInboxCandidatesMeta,
)


class TestFoiaInboxCandidatesMeta(unittest.TestCase):
    """FoiaInboxCandidatesMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoiaInboxCandidatesMeta:
        """Test FoiaInboxCandidatesMeta
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FoiaInboxCandidatesMeta`
        """
        model = FoiaInboxCandidatesMeta()
        if include_optional:
            return FoiaInboxCandidatesMeta(
                generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                filters_applied = { },
                current_page = 56,
                per_page = 56,
                max_per_page = 56,
                total_pages = 56,
                total_entries = 56,
                next_page = 56,
                previous_page = 56
            )
        else:
            return FoiaInboxCandidatesMeta(
                generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                current_page = 56,
                per_page = 56,
                max_per_page = 56,
                total_pages = 56,
                total_entries = 56,
        )
        """

    def testFoiaInboxCandidatesMeta(self):
        """Test FoiaInboxCandidatesMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
