# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.cashflow_group_item import CashflowGroupItem


class TestCashflowGroupItem(unittest.TestCase):
    """CashflowGroupItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashflowGroupItem:
        """Test CashflowGroupItem
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CashflowGroupItem`
        """
        model = CashflowGroupItem()
        if include_optional:
            return CashflowGroupItem(
                id = 56,
                name = '',
                name_id = '',
                short_name = ''
            )
        else:
            return CashflowGroupItem(
        )
        """

    def testCashflowGroupItem(self):
        """Test CashflowGroupItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
