# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.30864390916
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.foia_inbox_contact_changes import (
    FoiaInboxContactChanges,
)


class TestFoiaInboxContactChanges(unittest.TestCase):
    """FoiaInboxContactChanges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoiaInboxContactChanges:
        """Test FoiaInboxContactChanges
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FoiaInboxContactChanges`
        """
        model = FoiaInboxContactChanges()
        if include_optional:
            return FoiaInboxContactChanges(
                first_name = '0',
                last_name = '0',
                email = '',
                position = '',
                phone = '',
                mailing_address = '',
                contact_page_url = ''
            )
        else:
            return FoiaInboxContactChanges(
        )
        """

    def testFoiaInboxContactChanges(self):
        """Test FoiaInboxContactChanges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
