# coding: utf-8

"""
    Winthrop Intelligence Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import winthrop_client_python
from winthrop_client_python.api.default_api import DefaultApi  # noqa: E501
from winthrop_client_python.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = winthrop_client_python.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_foia_label(self):
        """Test case for create_foia_label"""
        pass

    def test_create_foia_request(self):
        """Test case for create_foia_request"""
        pass

    def test_create_requested_item(self):
        """Test case for create_requested_item"""
        pass

    def test_delete_foia_label(self):
        """Test case for delete_foia_label"""
        pass

    def test_delete_foia_request(self):
        """Test case for delete_foia_request"""
        pass

    def test_delete_requested_item(self):
        """Test case for delete_requested_item"""
        pass

    def test_get_audited_financial_report_status(self):
        """Test case for get_audited_financial_report_status"""
        pass

    def test_get_audited_financial_report_statuses(self):
        """Test case for get_audited_financial_report_statuses"""
        pass

    def test_get_coach(self):
        """Test case for get_coach"""
        pass

    def test_get_coaches(self):
        """Test case for get_coaches"""
        pass

    def test_get_compensation(self):
        """Test case for get_compensation"""
        pass

    def test_get_compensations(self):
        """Test case for get_compensations"""
        pass

    def test_get_deal_status(self):
        """Test case for get_deal_status"""
        pass

    def test_get_deal_statuses(self):
        """Test case for get_deal_statuses"""
        pass

    def test_get_foia_label(self):
        """Test case for get_foia_label"""
        pass

    def test_get_foia_labels(self):
        """Test case for get_foia_labels"""
        pass

    def test_get_foia_request(self):
        """Test case for get_foia_request"""
        pass

    def test_get_foia_requests(self):
        """Test case for get_foia_requests"""
        pass

    def test_get_game(self):
        """Test case for get_game"""
        pass

    def test_get_games(self):
        """Test case for get_games"""
        pass

    def test_get_income_report(self):
        """Test case for get_income_report"""
        pass

    def test_get_income_reports(self):
        """Test case for get_income_reports"""
        pass

    def test_get_ncaa_financial_report_status(self):
        """Test case for get_ncaa_financial_report_status"""
        pass

    def test_get_ncaa_financial_report_statuses(self):
        """Test case for get_ncaa_financial_report_statuses"""
        pass

    def test_get_requested_item(self):
        """Test case for get_requested_item"""
        pass

    def test_get_requested_items(self):
        """Test case for get_requested_items"""
        pass

    def test_get_school(self):
        """Test case for get_school"""
        pass

    def test_get_schools(self):
        """Test case for get_schools"""
        pass

    def test_get_user(self):
        """Test case for get_user"""
        pass

    def test_get_users(self):
        """Test case for get_users"""
        pass

    def test_summarizer_post_qa_s3(self):
        """Test case for summarizer_post_qa_s3

        Answer questions over a file from S3  # noqa: E501
        """
        pass

    def test_summarizer_post_summarize_s3(self):
        """Test case for summarizer_post_summarize_s3

        Summarize a file from S3  # noqa: E501
        """
        pass

    def test_update_foia_label(self):
        """Test case for update_foia_label"""
        pass

    def test_update_foia_request(self):
        """Test case for update_foia_request"""
        pass

    def test_update_requested_item(self):
        """Test case for update_requested_item"""
        pass


if __name__ == "__main__":
    unittest.main()
