# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.compensation_row import CompensationRow


class TestCompensationRow(unittest.TestCase):
    """CompensationRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompensationRow:
        """Test CompensationRow
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CompensationRow`
        """
        model = CompensationRow()
        if include_optional:
            return CompensationRow(
                id = 56,
                school_id = 56,
                school_name = '',
                coach_id = 56,
                coach_name = '',
                total_comp = 56,
                base_salary = 56,
                talent_fee = 1.337,
                outside_income = 56,
                contingent_bonus = True,
                car_provided = True,
                country_club = True,
                buyout_terms = '',
                contract_end = ''
            )
        else:
            return CompensationRow(
        )
        """

    def testCompensationRow(self):
        """Test CompensationRow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
