# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.15-dev.9330
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.game_post_gap_count_collection import (
    GamePostGapCountCollection,
)


class TestGamePostGapCountCollection(unittest.TestCase):
    """GamePostGapCountCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GamePostGapCountCollection:
        """Test GamePostGapCountCollection
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GamePostGapCountCollection`
        """
        model = GamePostGapCountCollection()
        if include_optional:
            return GamePostGapCountCollection(
                data = [
                    winthrop_client_python.models.game_post_gap_count_collection_data_inner.GamePostGapCountCollection_data_inner(
                        start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        count = 56, )
                    ]
            )
        else:
            return GamePostGapCountCollection(
        )
        """

    def testGamePostGapCountCollection(self):
        """Test GamePostGapCountCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
