# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.6-dev.58
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.gad_school_summary_school import (
    GadSchoolSummarySchool,
)


class TestGadSchoolSummarySchool(unittest.TestCase):
    """GadSchoolSummarySchool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GadSchoolSummarySchool:
        """Test GadSchoolSummarySchool
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GadSchoolSummarySchool`
        """
        model = GadSchoolSummarySchool()
        if include_optional:
            return GadSchoolSummarySchool(
                id = 56,
                name = '',
                short_name = ''
            )
        else:
            return GadSchoolSummarySchool(
        )
        """

    def testGadSchoolSummarySchool(self):
        """Test GadSchoolSummarySchool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
