# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.account_info import AccountInfo


class TestAccountInfo(unittest.TestCase):
    """AccountInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountInfo:
        """Test AccountInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AccountInfo`
        """
        model = AccountInfo()
        if include_optional:
            return AccountInfo(
                name = '',
                email_domain = '',
                accountable_type = '',
                accountable_id = 56
            )
        else:
            return AccountInfo(
        )
        """

    def testAccountInfo(self):
        """Test AccountInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
