# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.1-dev.10297
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.create_admin_desk_report_artifact201_response import (
    CreateAdminDeskReportArtifact201Response,
)


class TestCreateAdminDeskReportArtifact201Response(unittest.TestCase):
    """CreateAdminDeskReportArtifact201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> CreateAdminDeskReportArtifact201Response:
        """Test CreateAdminDeskReportArtifact201Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateAdminDeskReportArtifact201Response`
        """
        model = CreateAdminDeskReportArtifact201Response()
        if include_optional:
            return CreateAdminDeskReportArtifact201Response(
                data = winthrop_client_python.models.desk_admin_artifact.DeskAdminArtifact(
                    id = 56, 
                    kind = 'pdf', 
                    filename = '', 
                    byte_size = 56, 
                    url = '', )
            )
        else:
            return CreateAdminDeskReportArtifact201Response(
                data = winthrop_client_python.models.desk_admin_artifact.DeskAdminArtifact(
                    id = 56, 
                    kind = 'pdf', 
                    filename = '', 
                    byte_size = 56, 
                    url = '', ),
        )
        """

    def testCreateAdminDeskReportArtifact201Response(self):
        """Test CreateAdminDeskReportArtifact201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
