# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.42.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.game_post_collection import GamePostCollection


class TestGamePostCollection(unittest.TestCase):
    """GamePostCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GamePostCollection:
        """Test GamePostCollection
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GamePostCollection`
        """
        model = GamePostCollection()
        if include_optional:
            return GamePostCollection(
                data = [
                    winthrop_client_python.models.game_post.GamePost(
                        id = 56, 
                        school_id = 56, 
                        sport_id = 56, 
                        start_date = 'Mon Jan 01 00:00:00 UTC 2024', 
                        end_date = 'Wed Jan 31 00:00:00 UTC 2024', 
                        description = '', 
                        status = 'Active', 
                        expires_on = 'Fri Mar 15 00:00:00 UTC 2024', 
                        created_at = '2019-01-01T00:00Z', 
                        updated_at = '2019-01-01T00:00Z', 
                        game_types = [
                            winthrop_client_python.models.game_type.GameType(
                                id = 56, 
                                name = 'GuaranteeNeeded', 
                                name_display = 'Guarantee Needed', )
                            ], )
                    ],
                meta = winthrop_client_python.models.meta.Meta(
                    current_page = 2, 
                    total_pages = 7, 
                    total_entries = 654, 
                    next_page = 3, 
                    previous_page = 1, )
            )
        else:
            return GamePostCollection(
        )
        """

    def testGamePostCollection(self):
        """Test GamePostCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
