# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.30864390916
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.foia_inbox_contact import FoiaInboxContact


class TestFoiaInboxContact(unittest.TestCase):
    """FoiaInboxContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoiaInboxContact:
        """Test FoiaInboxContact
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FoiaInboxContact`
        """
        model = FoiaInboxContact()
        if include_optional:
            return FoiaInboxContact(
                id = 1,
                type = '',
                first_name = '',
                last_name = '',
                email = '',
                position = '',
                phone = '',
                mailing_address = '',
                contact_page_url = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FoiaInboxContact(
                id = 1,
                type = '',
                first_name = '',
                last_name = '',
                email = '',
                position = '',
                phone = '',
                mailing_address = '',
                contact_page_url = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testFoiaInboxContact(self):
        """Test FoiaInboxContact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
