# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.admin_meta import AdminMeta


class TestAdminMeta(unittest.TestCase):
    """AdminMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminMeta:
        """Test AdminMeta
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AdminMeta`
        """
        model = AdminMeta()
        if include_optional:
            return AdminMeta(
                current_page = 2,
                total_pages = 7,
                total_entries = 654,
                next_page = 3,
                previous_page = 1,
                comp_stats = winthrop_client_python.models.admin_meta_comp_stats.AdminMeta_comp_stats(
                    min = 500000, 
                    max = 324000000, 
                    average = 10413700, 
                    median = 7500000, )
            )
        else:
            return AdminMeta(
        )
        """

    def testAdminMeta(self):
        """Test AdminMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
