# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from winthrop_client_python.models.team_schedule_contact import TeamScheduleContact


class TestTeamScheduleContact(unittest.TestCase):
    """TeamScheduleContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamScheduleContact:
        """Test TeamScheduleContact
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TeamScheduleContact`
        """
        model = TeamScheduleContact()
        if include_optional:
            return TeamScheduleContact(
                coach_id = 56,
                name = '',
                title = '',
                email = '',
                phone = '',
                avatar_url = ''
            )
        else:
            return TeamScheduleContact(
        )
        """

    def testTeamScheduleContact(self):
        """Test TeamScheduleContact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
