# coding: utf-8

# flake8: noqa
"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from winthrop_client_python.models.account_billing_address import AccountBillingAddress
from winthrop_client_python.models.account_detail import AccountDetail
from winthrop_client_python.models.account_info import AccountInfo
from winthrop_client_python.models.account_invoice import AccountInvoice
from winthrop_client_python.models.account_subscription import AccountSubscription
from winthrop_client_python.models.account_user import AccountUser
from winthrop_client_python.models.account_users_response import AccountUsersResponse
from winthrop_client_python.models.admin_compensation_subdivision import (
    AdminCompensationSubdivision,
)
from winthrop_client_python.models.administrator import Administrator
from winthrop_client_python.models.administrator_collection import (
    AdministratorCollection,
)
from winthrop_client_python.models.administrator_search_result_collection import (
    AdministratorSearchResultCollection,
)
from winthrop_client_python.models.asst_coach_entry import AsstCoachEntry
from winthrop_client_python.models.asst_coach_school import AsstCoachSchool
from winthrop_client_python.models.athletic_profile_show import AthleticProfileShow
from winthrop_client_python.models.athletic_profile_show_contacts_inner import (
    AthleticProfileShowContactsInner,
)
from winthrop_client_python.models.athletic_profile_show_deals_inner import (
    AthleticProfileShowDealsInner,
)
from winthrop_client_python.models.athletic_profile_show_financial_info import (
    AthleticProfileShowFinancialInfo,
)
from winthrop_client_python.models.athletic_profile_show_financials import (
    AthleticProfileShowFinancials,
)
from winthrop_client_python.models.athletic_profile_show_financials_revenues_inner import (
    AthleticProfileShowFinancialsRevenuesInner,
)
from winthrop_client_python.models.athletic_profile_show_games_inner import (
    AthleticProfileShowGamesInner,
)
from winthrop_client_python.models.athletic_profile_show_guarantees_inner import (
    AthleticProfileShowGuaranteesInner,
)
from winthrop_client_python.models.athletic_profile_show_permissions import (
    AthleticProfileShowPermissions,
)
from winthrop_client_python.models.athletic_profile_show_personnel_inner import (
    AthleticProfileShowPersonnelInner,
)
from winthrop_client_python.models.athletic_profile_show_school import (
    AthleticProfileShowSchool,
)
from winthrop_client_python.models.athletic_profile_show_sports_overview_inner import (
    AthleticProfileShowSportsOverviewInner,
)
from winthrop_client_python.models.athletic_profile_show_tab_sports_inner import (
    AthleticProfileShowTabSportsInner,
)
from winthrop_client_python.models.audited_financial_report_status import (
    AuditedFinancialReportStatus,
)
from winthrop_client_python.models.audited_financial_report_status_collection import (
    AuditedFinancialReportStatusCollection,
)
from winthrop_client_python.models.avatar import Avatar
from winthrop_client_python.models.average_compensation import AverageCompensation
from winthrop_client_python.models.coli_adjusted import COLIAdjusted
from winthrop_client_python.models.cashflow import Cashflow
from winthrop_client_python.models.cashflow_collection import CashflowCollection
from winthrop_client_python.models.cashflow_group_item import CashflowGroupItem
from winthrop_client_python.models.cashflow_group_stats import CashflowGroupStats
from winthrop_client_python.models.cashflow_groups_response import (
    CashflowGroupsResponse,
)
from winthrop_client_python.models.cashflow_sport_stat import CashflowSportStat
from winthrop_client_python.models.category import Category
from winthrop_client_python.models.category_collection import CategoryCollection
from winthrop_client_python.models.coach import Coach
from winthrop_client_python.models.coach_collection import CoachCollection
from winthrop_client_python.models.coach_compensation import CoachCompensation
from winthrop_client_python.models.coach_compensation_entry import (
    CoachCompensationEntry,
)
from winthrop_client_python.models.coach_compensation_tab import CoachCompensationTab
from winthrop_client_python.models.coach_compensation_tab_chart_data import (
    CoachCompensationTabChartData,
)
from winthrop_client_python.models.coach_compensation_tab_chart_data_conference_avg_over_time_inner import (
    CoachCompensationTabChartDataConferenceAvgOverTimeInner,
)
from winthrop_client_python.models.coach_compensation_tab_chart_data_current_breakdown import (
    CoachCompensationTabChartDataCurrentBreakdown,
)
from winthrop_client_python.models.coach_compensation_tab_chart_data_total_comp_over_time_inner import (
    CoachCompensationTabChartDataTotalCompOverTimeInner,
)
from winthrop_client_python.models.coach_compensation_tab_comparisons import (
    CoachCompensationTabComparisons,
)
from winthrop_client_python.models.coach_compensation_tab_sidebar import (
    CoachCompensationTabSidebar,
)
from winthrop_client_python.models.coach_compensation_tab_sidebar_coaching_staff_inner import (
    CoachCompensationTabSidebarCoachingStaffInner,
)
from winthrop_client_python.models.coach_compensation_tab_sidebar_contracts_inner import (
    CoachCompensationTabSidebarContractsInner,
)
from winthrop_client_python.models.coach_compensation_tab_sidebar_income_reports_inner import (
    CoachCompensationTabSidebarIncomeReportsInner,
)
from winthrop_client_python.models.coach_coworker_history_tab import (
    CoachCoworkerHistoryTab,
)
from winthrop_client_python.models.coach_position_entry import CoachPositionEntry
from winthrop_client_python.models.coach_profile import CoachProfile
from winthrop_client_python.models.coach_profile_overview import CoachProfileOverview
from winthrop_client_python.models.coach_record_tab import CoachRecordTab
from winthrop_client_python.models.coach_recruiting_tab import CoachRecruitingTab
from winthrop_client_python.models.coach_recruiting_tab_conference_comparison import (
    CoachRecruitingTabConferenceComparison,
)
from winthrop_client_python.models.coach_recruiting_tab_metadata import (
    CoachRecruitingTabMetadata,
)
from winthrop_client_python.models.coach_recruiting_tab_recruiting_budgets import (
    CoachRecruitingTabRecruitingBudgets,
)
from winthrop_client_python.models.coach_search_result import CoachSearchResult
from winthrop_client_python.models.coach_search_result_collection import (
    CoachSearchResultCollection,
)
from winthrop_client_python.models.coach_snapshot import CoachSnapshot
from winthrop_client_python.models.coach_video_entry import CoachVideoEntry
from winthrop_client_python.models.coach_videos_tab import CoachVideosTab
from winthrop_client_python.models.coli_data import ColiData
from winthrop_client_python.models.comp_stats import CompStats
from winthrop_client_python.models.compare_coli404_response import (
    CompareColi404Response,
)
from winthrop_client_python.models.compare_coli422_response import (
    CompareColi422Response,
)
from winthrop_client_python.models.comparison_section import ComparisonSection
from winthrop_client_python.models.comparison_section_coaches_inner import (
    ComparisonSectionCoachesInner,
)
from winthrop_client_python.models.compensation import Compensation
from winthrop_client_python.models.compensation_collection import CompensationCollection
from winthrop_client_python.models.compensation_row import CompensationRow
from winthrop_client_python.models.conference import Conference
from winthrop_client_python.models.conference_admin_compensation_response import (
    ConferenceAdminCompensationResponse,
)
from winthrop_client_python.models.conference_cashflow_stats_response import (
    ConferenceCashflowStatsResponse,
)
from winthrop_client_python.models.conference_collection import ConferenceCollection
from winthrop_client_python.models.conference_department_staff_response import (
    ConferenceDepartmentStaffResponse,
)
from winthrop_client_python.models.conference_directors_cup_response import (
    ConferenceDirectorsCupResponse,
)
from winthrop_client_python.models.conference_position_entry import (
    ConferencePositionEntry,
)
from winthrop_client_python.models.conference_position_stats_response import (
    ConferencePositionStatsResponse,
)
from winthrop_client_python.models.conferenceship import Conferenceship
from winthrop_client_python.models.conferenceship_collection import (
    ConferenceshipCollection,
)
from winthrop_client_python.models.contact import Contact
from winthrop_client_python.models.contact_collection import ContactCollection
from winthrop_client_python.models.contact_search_coach_options import (
    ContactSearchCoachOptions,
)
from winthrop_client_python.models.contact_search_coach_options_coaches_inner import (
    ContactSearchCoachOptionsCoachesInner,
)
from winthrop_client_python.models.contact_search_coach_options_sports_inner import (
    ContactSearchCoachOptionsSportsInner,
)
from winthrop_client_python.models.contact_search_collection import (
    ContactSearchCollection,
)
from winthrop_client_python.models.contact_search_entry import ContactSearchEntry
from winthrop_client_python.models.contract import Contract
from winthrop_client_python.models.contract_collection import ContractCollection
from winthrop_client_python.models.coworker_entry import CoworkerEntry
from winthrop_client_python.models.coworker_tenure import CoworkerTenure
from winthrop_client_python.models.create_account_user422_response import (
    CreateAccountUser422Response,
)
from winthrop_client_python.models.create_account_user_request import (
    CreateAccountUserRequest,
)
from winthrop_client_python.models.create_account_user_request_user import (
    CreateAccountUserRequestUser,
)
from winthrop_client_python.models.create_contact_search_request import (
    CreateContactSearchRequest,
)
from winthrop_client_python.models.create_contact_search_request_contact import (
    CreateContactSearchRequestContact,
)
from winthrop_client_python.models.create_favorite201_response import (
    CreateFavorite201Response,
)
from winthrop_client_python.models.create_favorite_request import CreateFavoriteRequest
from winthrop_client_python.models.create_favorites_category_request import (
    CreateFavoritesCategoryRequest,
)
from winthrop_client_python.models.create_game_post_search_request import (
    CreateGamePostSearchRequest,
)
from winthrop_client_python.models.create_game_post_search_request_game_post import (
    CreateGamePostSearchRequestGamePost,
)
from winthrop_client_python.models.create_game_request import CreateGameRequest
from winthrop_client_python.models.create_game_request_game import CreateGameRequestGame
from winthrop_client_python.models.create_note_request import CreateNoteRequest
from winthrop_client_python.models.create_password_reset200_response import (
    CreatePasswordReset200Response,
)
from winthrop_client_python.models.create_password_reset_request import (
    CreatePasswordResetRequest,
)
from winthrop_client_python.models.create_password_reset_request_user import (
    CreatePasswordResetRequestUser,
)
from winthrop_client_python.models.create_school_group_request import (
    CreateSchoolGroupRequest,
)
from winthrop_client_python.models.create_school_group_request_school_group import (
    CreateSchoolGroupRequestSchoolGroup,
)
from winthrop_client_python.models.create_team_schedule_favorite201_response import (
    CreateTeamScheduleFavorite201Response,
)
from winthrop_client_python.models.create_team_schedule_favorite_request import (
    CreateTeamScheduleFavoriteRequest,
)
from winthrop_client_python.models.create_upload201_response import (
    CreateUpload201Response,
)
from winthrop_client_python.models.deal import Deal
from winthrop_client_python.models.deal_collection import DealCollection
from winthrop_client_python.models.deal_detail import DealDetail
from winthrop_client_python.models.deal_detail_vendor import DealDetailVendor
from winthrop_client_python.models.deal_search_result import DealSearchResult
from winthrop_client_python.models.deal_search_result_collection import (
    DealSearchResultCollection,
)
from winthrop_client_python.models.deal_status import DealStatus
from winthrop_client_python.models.deal_status_collection import DealStatusCollection
from winthrop_client_python.models.delete_account_user200_response import (
    DeleteAccountUser200Response,
)
from winthrop_client_python.models.delete_contact_search200_response import (
    DeleteContactSearch200Response,
)
from winthrop_client_python.models.delete_favorite200_response import (
    DeleteFavorite200Response,
)
from winthrop_client_python.models.department_search_result import (
    DepartmentSearchResult,
)
from winthrop_client_python.models.department_search_result_collection import (
    DepartmentSearchResultCollection,
)
from winthrop_client_python.models.department_search_result_department import (
    DepartmentSearchResultDepartment,
)
from winthrop_client_python.models.department_search_result_department_deals_inner import (
    DepartmentSearchResultDepartmentDealsInner,
)
from winthrop_client_python.models.department_search_result_sports_inner import (
    DepartmentSearchResultSportsInner,
)
from winthrop_client_python.models.department_staff_member import DepartmentStaffMember
from winthrop_client_python.models.department_staff_school import DepartmentStaffSchool
from winthrop_client_python.models.directors_cup_school import DirectorsCupSchool
from winthrop_client_python.models.division import Division
from winthrop_client_python.models.division_collection import DivisionCollection
from winthrop_client_python.models.dossier_report_response import DossierReportResponse
from winthrop_client_python.models.edit_account_user import EditAccountUser
from winthrop_client_python.models.edit_account_user_response import (
    EditAccountUserResponse,
)
from winthrop_client_python.models.filter_position_type import FilterPositionType
from winthrop_client_python.models.filters import Filters
from winthrop_client_python.models.financial_qc import FinancialQc
from winthrop_client_python.models.financial_search_result import FinancialSearchResult
from winthrop_client_python.models.financial_search_result_collection import (
    FinancialSearchResultCollection,
)
from winthrop_client_python.models.foia_label import FoiaLabel
from winthrop_client_python.models.foia_label_collection import FoiaLabelCollection
from winthrop_client_python.models.foia_request import FoiaRequest
from winthrop_client_python.models.foia_request_collection import FoiaRequestCollection
from winthrop_client_python.models.gad_contract_detail import GadContractDetail
from winthrop_client_python.models.gad_search_result import GadSearchResult
from winthrop_client_python.models.gad_search_result_collection import (
    GadSearchResultCollection,
)
from winthrop_client_python.models.gad_search_stats import GadSearchStats
from winthrop_client_python.models.game import Game
from winthrop_client_python.models.game_collection import GameCollection
from winthrop_client_python.models.game_contract import GameContract
from winthrop_client_python.models.game_contract_collection import (
    GameContractCollection,
)
from winthrop_client_python.models.game_contract_series_entry import (
    GameContractSeriesEntry,
)
from winthrop_client_python.models.game_contract_series_response import (
    GameContractSeriesResponse,
)
from winthrop_client_python.models.game_detail import GameDetail
from winthrop_client_python.models.game_detail_all_of_game_contract import (
    GameDetailAllOfGameContract,
)
from winthrop_client_python.models.game_post import GamePost
from winthrop_client_python.models.game_post_collection import GamePostCollection
from winthrop_client_python.models.game_post_contact import GamePostContact
from winthrop_client_python.models.game_post_detail import GamePostDetail
from winthrop_client_python.models.game_post_detail_created_by import (
    GamePostDetailCreatedBy,
)
from winthrop_client_python.models.game_post_search_result import GamePostSearchResult
from winthrop_client_python.models.game_post_search_result_collection import (
    GamePostSearchResultCollection,
)
from winthrop_client_python.models.game_type import GameType
from winthrop_client_python.models.geo_region import GeoRegion
from winthrop_client_python.models.get_account_user_activation200_response import (
    GetAccountUserActivation200Response,
)
from winthrop_client_python.models.get_favorites200_response_inner import (
    GetFavorites200ResponseInner,
)
from winthrop_client_python.models.get_favorites_categories200_response_inner import (
    GetFavoritesCategories200ResponseInner,
)
from winthrop_client_python.models.get_filter_options200_response import (
    GetFilterOptions200Response,
)
from winthrop_client_python.models.get_lad_filter_options200_response import (
    GetLadFilterOptions200Response,
)
from winthrop_client_python.models.get_lad_filter_options200_response_position_types_inner import (
    GetLadFilterOptions200ResponsePositionTypesInner,
)
from winthrop_client_python.models.get_school_alternate_names200_response import (
    GetSchoolAlternateNames200Response,
)
from winthrop_client_python.models.get_school_alternate_names404_response import (
    GetSchoolAlternateNames404Response,
)
from winthrop_client_python.models.get_team_schedule_favorites200_response_inner import (
    GetTeamScheduleFavorites200ResponseInner,
)
from winthrop_client_python.models.get_time_zones200_response import (
    GetTimeZones200Response,
)
from winthrop_client_python.models.get_wire_changes200_response import (
    GetWireChanges200Response,
)
from winthrop_client_python.models.http_validation_error import HTTPValidationError
from winthrop_client_python.models.health_check_failure import HealthCheckFailure
from winthrop_client_python.models.health_check_success import HealthCheckSuccess
from winthrop_client_python.models.id_name import IdName
from winthrop_client_python.models.income_report import IncomeReport
from winthrop_client_python.models.income_report_collection import (
    IncomeReportCollection,
)
from winthrop_client_python.models.job import Job
from winthrop_client_python.models.job_candidate import JobCandidate
from winthrop_client_python.models.job_collection import JobCollection
from winthrop_client_python.models.job_department import JobDepartment
from winthrop_client_python.models.job_post import JobPost
from winthrop_client_python.models.job_post_collection import JobPostCollection
from winthrop_client_python.models.job_school import JobSchool
from winthrop_client_python.models.job_sport import JobSport
from winthrop_client_python.models.link import Link
from winthrop_client_python.models.link_collection import LinkCollection
from winthrop_client_python.models.link_collection1 import LinkCollection1
from winthrop_client_python.models.list_notes200_response_inner import (
    ListNotes200ResponseInner,
)
from winthrop_client_python.models.location_inner import LocationInner
from winthrop_client_python.models.logo import Logo
from winthrop_client_python.models.meta import Meta
from winthrop_client_python.models.ncaa_financial_report_status import (
    NcaaFinancialReportStatus,
)
from winthrop_client_python.models.ncaa_financial_report_status_collection import (
    NcaaFinancialReportStatusCollection,
)
from winthrop_client_python.models.new_account_user_response import (
    NewAccountUserResponse,
)
from winthrop_client_python.models.news_feed import NewsFeed
from winthrop_client_python.models.news_feed_collection import NewsFeedCollection
from winthrop_client_python.models.note import Note
from winthrop_client_python.models.performance_chart_coach import PerformanceChartCoach
from winthrop_client_python.models.performance_chart_data import PerformanceChartData
from winthrop_client_python.models.performance_chart_record import (
    PerformanceChartRecord,
)
from winthrop_client_python.models.position import Position
from winthrop_client_python.models.position_collection import PositionCollection
from winthrop_client_python.models.position_sport_stat import PositionSportStat
from winthrop_client_python.models.position_type import PositionType
from winthrop_client_python.models.position_type_group import PositionTypeGroup
from winthrop_client_python.models.predict_body import PredictBody
from winthrop_client_python.models.predict_failure import PredictFailure
from winthrop_client_python.models.predict_success import PredictSuccess
from winthrop_client_python.models.raw_contract import RawContract
from winthrop_client_python.models.raw_contract_back_to import RawContractBackTo
from winthrop_client_python.models.raw_contract_collection import RawContractCollection
from winthrop_client_python.models.raw_contract_deal_info import RawContractDealInfo
from winthrop_client_python.models.record_position_entry import RecordPositionEntry
from winthrop_client_python.models.recruiting_budget_entry import RecruitingBudgetEntry
from winthrop_client_python.models.recruiting_chart_data import RecruitingChartData
from winthrop_client_python.models.recruiting_conference_entry import (
    RecruitingConferenceEntry,
)
from winthrop_client_python.models.recruiting_position_entry import (
    RecruitingPositionEntry,
)
from winthrop_client_python.models.regenerate_raw_contract_pdf200_response import (
    RegenerateRawContractPdf200Response,
)
from winthrop_client_python.models.requested_item import RequestedItem
from winthrop_client_python.models.requested_item_collection import (
    RequestedItemCollection,
)
from winthrop_client_python.models.role_option import RoleOption
from winthrop_client_python.models.schedule_grid_available_school_post import (
    ScheduleGridAvailableSchoolPost,
)
from winthrop_client_python.models.schedule_grid_available_school_row import (
    ScheduleGridAvailableSchoolRow,
)
from winthrop_client_python.models.schedule_grid_available_schools import (
    ScheduleGridAvailableSchools,
)
from winthrop_client_python.models.schedule_grid_game import ScheduleGridGame
from winthrop_client_python.models.schedule_grid_game_post import ScheduleGridGamePost
from winthrop_client_python.models.schedule_grid_school import ScheduleGridSchool
from winthrop_client_python.models.schedule_grid_view import ScheduleGridView
from winthrop_client_python.models.school import School
from winthrop_client_python.models.school_collection import SchoolCollection
from winthrop_client_python.models.school_contract_entry import SchoolContractEntry
from winthrop_client_python.models.school_financial_detail import SchoolFinancialDetail
from winthrop_client_python.models.school_financial_detail_group import (
    SchoolFinancialDetailGroup,
)
from winthrop_client_python.models.school_financial_detail_sibling import (
    SchoolFinancialDetailSibling,
)
from winthrop_client_python.models.school_financial_detail_sport import (
    SchoolFinancialDetailSport,
)
from winthrop_client_python.models.school_financial_group import SchoolFinancialGroup
from winthrop_client_python.models.school_financial_summary import (
    SchoolFinancialSummary,
)
from winthrop_client_python.models.school_game_contracts_response import (
    SchoolGameContractsResponse,
)
from winthrop_client_python.models.school_game_contracts_response_school import (
    SchoolGameContractsResponseSchool,
)
from winthrop_client_python.models.school_group_show import SchoolGroupShow
from winthrop_client_python.models.school_info import SchoolInfo
from winthrop_client_python.models.school_no_comp import SchoolNoComp
from winthrop_client_python.models.school_no_season import SchoolNoSeason
from winthrop_client_python.models.school_sport_season import SchoolSportSeason
from winthrop_client_python.models.school_sport_section import SchoolSportSection
from winthrop_client_python.models.school_wl_chart_point import SchoolWLChartPoint
from winthrop_client_python.models.scraper import Scraper
from winthrop_client_python.models.scraper_arg_def import ScraperArgDef
from winthrop_client_python.models.season import Season
from winthrop_client_python.models.season_collection import SeasonCollection
from winthrop_client_python.models.send_otp_code422_response import (
    SendOtpCode422Response,
)
from winthrop_client_python.models.snapshot_income_report import SnapshotIncomeReport
from winthrop_client_python.models.sport import Sport
from winthrop_client_python.models.sport_collection import SportCollection
from winthrop_client_python.models.sport_compensation_rankings import (
    SportCompensationRankings,
)
from winthrop_client_python.models.sport_compensation_rankings_schools_inner import (
    SportCompensationRankingsSchoolsInner,
)
from winthrop_client_python.models.sport_compensation_response import (
    SportCompensationResponse,
)
from winthrop_client_python.models.sport_compensation_subdivision import (
    SportCompensationSubdivision,
)
from winthrop_client_python.models.sport_option import SportOption
from winthrop_client_python.models.subdivision import Subdivision
from winthrop_client_python.models.subdivision_collection import SubdivisionCollection
from winthrop_client_python.models.subscription import Subscription
from winthrop_client_python.models.subscription_collection import SubscriptionCollection
from winthrop_client_python.models.system_setting import SystemSetting
from winthrop_client_python.models.tag import Tag
from winthrop_client_python.models.team_schedule_coaches import TeamScheduleCoaches
from winthrop_client_python.models.team_schedule_coaches_coaches_inner import (
    TeamScheduleCoachesCoachesInner,
)
from winthrop_client_python.models.team_schedule_coaches_head_coaches_inner_inner import (
    TeamScheduleCoachesHeadCoachesInnerInner,
)
from winthrop_client_python.models.team_schedule_coaches_seasons_inner import (
    TeamScheduleCoachesSeasonsInner,
)
from winthrop_client_python.models.team_schedule_contact import TeamScheduleContact
from winthrop_client_python.models.team_schedule_detail import TeamScheduleDetail
from winthrop_client_python.models.team_schedule_detail_game import (
    TeamScheduleDetailGame,
)
from winthrop_client_python.models.team_schedule_detail_head_coach import (
    TeamScheduleDetailHeadCoach,
)
from winthrop_client_python.models.team_schedule_detail_school import (
    TeamScheduleDetailSchool,
)
from winthrop_client_python.models.team_schedule_detail_season import (
    TeamScheduleDetailSeason,
)
from winthrop_client_python.models.team_schedule_favorite_detail import (
    TeamScheduleFavoriteDetail,
)
from winthrop_client_python.models.team_schedule_favorite_entry import (
    TeamScheduleFavoriteEntry,
)
from winthrop_client_python.models.team_schedule_game_posts import TeamScheduleGamePosts
from winthrop_client_python.models.team_schedule_game_posts_game_posts_inner import (
    TeamScheduleGamePostsGamePostsInner,
)
from winthrop_client_python.models.team_schedule_note import TeamScheduleNote
from winthrop_client_python.models.team_schedule_overlap import TeamScheduleOverlap
from winthrop_client_python.models.team_schedule_overlap_team_games_inner import (
    TeamScheduleOverlapTeamGamesInner,
)
from winthrop_client_python.models.team_schedule_player_data import (
    TeamSchedulePlayerData,
)
from winthrop_client_python.models.team_schedule_player_data_recruits_inner import (
    TeamSchedulePlayerDataRecruitsInner,
)
from winthrop_client_python.models.team_schedule_player_data_returning_pct import (
    TeamSchedulePlayerDataReturningPct,
)
from winthrop_client_python.models.team_schedule_player_data_returning_players_inner import (
    TeamSchedulePlayerDataReturningPlayersInner,
)
from winthrop_client_python.models.team_schedule_player_data_transfers_inner import (
    TeamSchedulePlayerDataTransfersInner,
)
from winthrop_client_python.models.team_schedule_recent_contract import (
    TeamScheduleRecentContract,
)
from winthrop_client_python.models.team_schedule_schedule import TeamScheduleSchedule
from winthrop_client_python.models.team_schedule_schedule_games_inner import (
    TeamScheduleScheduleGamesInner,
)
from winthrop_client_python.models.team_schedule_search_result import (
    TeamScheduleSearchResult,
)
from winthrop_client_python.models.team_schedule_search_result_away_contracts import (
    TeamScheduleSearchResultAwayContracts,
)
from winthrop_client_python.models.team_schedule_search_result_collection import (
    TeamScheduleSearchResultCollection,
)
from winthrop_client_python.models.team_schedule_search_result_home_contracts import (
    TeamScheduleSearchResultHomeContracts,
)
from winthrop_client_python.models.time_zone_option import TimeZoneOption
from winthrop_client_python.models.unauthorized_error import UnauthorizedError
from winthrop_client_python.models.unprocessable_entity import UnprocessableEntity
from winthrop_client_python.models.unstract_raw_contract_pdf_text_request import (
    UnstractRawContractPdfTextRequest,
)
from winthrop_client_python.models.update_account_user_activation200_response import (
    UpdateAccountUserActivation200Response,
)
from winthrop_client_python.models.update_account_user_activation_request import (
    UpdateAccountUserActivationRequest,
)
from winthrop_client_python.models.update_account_user_activation_request_user import (
    UpdateAccountUserActivationRequestUser,
)
from winthrop_client_python.models.update_account_user_request import (
    UpdateAccountUserRequest,
)
from winthrop_client_python.models.update_account_user_request_user import (
    UpdateAccountUserRequestUser,
)
from winthrop_client_python.models.update_favorite_request import UpdateFavoriteRequest
from winthrop_client_python.models.update_favorites_category_request import (
    UpdateFavoritesCategoryRequest,
)
from winthrop_client_python.models.update_game_post_search_request import (
    UpdateGamePostSearchRequest,
)
from winthrop_client_python.models.update_game_post_search_request_game_post import (
    UpdateGamePostSearchRequestGamePost,
)
from winthrop_client_python.models.update_note_request import UpdateNoteRequest
from winthrop_client_python.models.update_password_reset200_response import (
    UpdatePasswordReset200Response,
)
from winthrop_client_python.models.update_password_reset_request import (
    UpdatePasswordResetRequest,
)
from winthrop_client_python.models.update_password_reset_request_user import (
    UpdatePasswordResetRequestUser,
)
from winthrop_client_python.models.update_school_group_request import (
    UpdateSchoolGroupRequest,
)
from winthrop_client_python.models.update_school_group_request_school_group import (
    UpdateSchoolGroupRequestSchoolGroup,
)
from winthrop_client_python.models.update_team_schedule_favorite_request import (
    UpdateTeamScheduleFavoriteRequest,
)
from winthrop_client_python.models.update_user_request import UpdateUserRequest
from winthrop_client_python.models.update_user_request_user import UpdateUserRequestUser
from winthrop_client_python.models.upload_detail import UploadDetail
from winthrop_client_python.models.upload_item import UploadItem
from winthrop_client_python.models.uploads_response import UploadsResponse
from winthrop_client_python.models.upsert_team_schedule_note_request import (
    UpsertTeamScheduleNoteRequest,
)
from winthrop_client_python.models.user import User
from winthrop_client_python.models.user_activity_summary import UserActivitySummary
from winthrop_client_python.models.user_activity_summary_collection import (
    UserActivitySummaryCollection,
)
from winthrop_client_python.models.user_collection import UserCollection
from winthrop_client_python.models.user_request import UserRequest
from winthrop_client_python.models.user_request_collection import UserRequestCollection
from winthrop_client_python.models.user_schedule_sports_inner import (
    UserScheduleSportsInner,
)
from winthrop_client_python.models.validation_error import ValidationError
from winthrop_client_python.models.vendor import Vendor
from winthrop_client_python.models.vendor_collection import VendorCollection
from winthrop_client_python.models.verify_otp_code200_response import (
    VerifyOtpCode200Response,
)
from winthrop_client_python.models.verify_otp_code_request import VerifyOtpCodeRequest
from winthrop_client_python.models.verify_user_intercollegiate_access200_response import (
    VerifyUserIntercollegiateAccess200Response,
)
from winthrop_client_python.models.video_entry import VideoEntry
from winthrop_client_python.models.wire_change import WireChange
from winthrop_client_python.models.wire_change_coach import WireChangeCoach
from winthrop_client_python.models.wire_change_school import WireChangeSchool
