# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.conference_position_entry import (
    ConferencePositionEntry,
)
from winthrop_client_python.models.performance_chart_data import PerformanceChartData
from winthrop_client_python.models.record_position_entry import RecordPositionEntry
from typing import Optional, Set
from typing_extensions import Self


class CoachRecordTab(BaseModel):
    """
    CoachRecordTab
    """  # noqa: E501

    leader_ad: StrictBool
    show_coach_apr: StrictBool
    positions_by_sport: Dict[str, List[RecordPositionEntry]]
    conference_positions_by_sport: Dict[str, List[ConferencePositionEntry]]
    performance_chart: Optional[PerformanceChartData] = None
    __properties: ClassVar[List[str]] = [
        "leader_ad",
        "show_coach_apr",
        "positions_by_sport",
        "conference_positions_by_sport",
        "performance_chart",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoachRecordTab from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in positions_by_sport (dict of array)
        _field_dict_of_array = {}
        if self.positions_by_sport:
            for _key_positions_by_sport in self.positions_by_sport:
                if self.positions_by_sport[_key_positions_by_sport] is not None:
                    _field_dict_of_array[_key_positions_by_sport] = [
                        _item.to_dict()
                        for _item in self.positions_by_sport[_key_positions_by_sport]
                    ]
            _dict["positions_by_sport"] = _field_dict_of_array
        # override the default output from pydantic by calling `to_dict()` of each value in conference_positions_by_sport (dict of array)
        _field_dict_of_array = {}
        if self.conference_positions_by_sport:
            for (
                _key_conference_positions_by_sport
            ) in self.conference_positions_by_sport:
                if (
                    self.conference_positions_by_sport[
                        _key_conference_positions_by_sport
                    ]
                    is not None
                ):
                    _field_dict_of_array[_key_conference_positions_by_sport] = [
                        _item.to_dict()
                        for _item in self.conference_positions_by_sport[
                            _key_conference_positions_by_sport
                        ]
                    ]
            _dict["conference_positions_by_sport"] = _field_dict_of_array
        # override the default output from pydantic by calling `to_dict()` of performance_chart
        if self.performance_chart:
            _dict["performance_chart"] = self.performance_chart.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoachRecordTab from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "leader_ad": obj.get("leader_ad"),
                "show_coach_apr": obj.get("show_coach_apr"),
                "positions_by_sport": dict(
                    (
                        _k,
                        (
                            [RecordPositionEntry.from_dict(_item) for _item in _v]
                            if _v is not None
                            else None
                        ),
                    )
                    for _k, _v in obj.get("positions_by_sport", {}).items()
                ),
                "conference_positions_by_sport": dict(
                    (
                        _k,
                        (
                            [ConferencePositionEntry.from_dict(_item) for _item in _v]
                            if _v is not None
                            else None
                        ),
                    )
                    for _k, _v in obj.get("conference_positions_by_sport", {}).items()
                ),
                "performance_chart": (
                    PerformanceChartData.from_dict(obj["performance_chart"])
                    if obj.get("performance_chart") is not None
                    else None
                ),
            }
        )
        return _obj
