# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class CoachCompensationTabQuartilesRowsInner(BaseModel):
    """
    CoachCompensationTabQuartilesRowsInner
    """  # noqa: E501

    group: Optional[StrictStr] = None
    percent_rank: Optional[StrictInt] = None
    q25_cents: StrictInt
    q50_cents: StrictInt
    q75_cents: StrictInt
    q100_cents: StrictInt
    __properties: ClassVar[List[str]] = [
        "group",
        "percent_rank",
        "q25_cents",
        "q50_cents",
        "q75_cents",
        "q100_cents",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoachCompensationTabQuartilesRowsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if group (nullable) is None
        # and model_fields_set contains the field
        if self.group is None and "group" in self.model_fields_set:
            _dict["group"] = None

        # set to None if percent_rank (nullable) is None
        # and model_fields_set contains the field
        if self.percent_rank is None and "percent_rank" in self.model_fields_set:
            _dict["percent_rank"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoachCompensationTabQuartilesRowsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "group": obj.get("group"),
                "percent_rank": obj.get("percent_rank"),
                "q25_cents": obj.get("q25_cents"),
                "q50_cents": obj.get("q50_cents"),
                "q75_cents": obj.get("q75_cents"),
                "q100_cents": obj.get("q100_cents"),
            }
        )
        return _obj
