# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.admin_compensation_subdivision import (
    AdminCompensationSubdivision,
)
from winthrop_client_python.models.compensation_row import CompensationRow
from winthrop_client_python.models.id_name import IdName
from winthrop_client_python.models.school_no_comp import SchoolNoComp
from winthrop_client_python.models.school_no_season import SchoolNoSeason
from typing import Optional, Set
from typing_extensions import Self


class ConferenceAdminCompensationResponse(BaseModel):
    """
    ConferenceAdminCompensationResponse
    """  # noqa: E501

    year: Optional[StrictInt] = None
    departments: Optional[List[IdName]] = None
    leader_ad_positions: Optional[List[IdName]] = None
    compensations: Optional[List[CompensationRow]] = None
    schools_no_comp: Optional[List[SchoolNoComp]] = None
    schools_no_season: Optional[List[SchoolNoSeason]] = None
    subdivisions: Optional[List[AdminCompensationSubdivision]] = None
    __properties: ClassVar[List[str]] = [
        "year",
        "departments",
        "leader_ad_positions",
        "compensations",
        "schools_no_comp",
        "schools_no_season",
        "subdivisions",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConferenceAdminCompensationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in departments (list)
        _items = []
        if self.departments:
            for _item_departments in self.departments:
                if _item_departments:
                    _items.append(_item_departments.to_dict())
            _dict["departments"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in leader_ad_positions (list)
        _items = []
        if self.leader_ad_positions:
            for _item_leader_ad_positions in self.leader_ad_positions:
                if _item_leader_ad_positions:
                    _items.append(_item_leader_ad_positions.to_dict())
            _dict["leader_ad_positions"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in compensations (list)
        _items = []
        if self.compensations:
            for _item_compensations in self.compensations:
                if _item_compensations:
                    _items.append(_item_compensations.to_dict())
            _dict["compensations"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in schools_no_comp (list)
        _items = []
        if self.schools_no_comp:
            for _item_schools_no_comp in self.schools_no_comp:
                if _item_schools_no_comp:
                    _items.append(_item_schools_no_comp.to_dict())
            _dict["schools_no_comp"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in schools_no_season (list)
        _items = []
        if self.schools_no_season:
            for _item_schools_no_season in self.schools_no_season:
                if _item_schools_no_season:
                    _items.append(_item_schools_no_season.to_dict())
            _dict["schools_no_season"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in subdivisions (list)
        _items = []
        if self.subdivisions:
            for _item_subdivisions in self.subdivisions:
                if _item_subdivisions:
                    _items.append(_item_subdivisions.to_dict())
            _dict["subdivisions"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConferenceAdminCompensationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "year": obj.get("year"),
                "departments": (
                    [IdName.from_dict(_item) for _item in obj["departments"]]
                    if obj.get("departments") is not None
                    else None
                ),
                "leader_ad_positions": (
                    [IdName.from_dict(_item) for _item in obj["leader_ad_positions"]]
                    if obj.get("leader_ad_positions") is not None
                    else None
                ),
                "compensations": (
                    [CompensationRow.from_dict(_item) for _item in obj["compensations"]]
                    if obj.get("compensations") is not None
                    else None
                ),
                "schools_no_comp": (
                    [SchoolNoComp.from_dict(_item) for _item in obj["schools_no_comp"]]
                    if obj.get("schools_no_comp") is not None
                    else None
                ),
                "schools_no_season": (
                    [
                        SchoolNoSeason.from_dict(_item)
                        for _item in obj["schools_no_season"]
                    ]
                    if obj.get("schools_no_season") is not None
                    else None
                ),
                "subdivisions": (
                    [
                        AdminCompensationSubdivision.from_dict(_item)
                        for _item in obj["subdivisions"]
                    ]
                    if obj.get("subdivisions") is not None
                    else None
                ),
            }
        )
        return _obj
