# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.63
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from winthrop_client_python.models.department_financials_eada_role import (
    DepartmentFinancialsEadaRole,
)
from typing import Optional, Set
from typing_extensions import Self


class DepartmentFinancialsEadaCoaching(BaseModel):
    """
    EADA institution-wide coaching aggregates. Public federal data, so it is not subject to NCAA cashflow suppression and is present for private schools too
    """  # noqa: E501

    year: StrictInt
    total_salary_pool_cents: StrictInt = Field(
        description="Derived as the sum of each displayed average multiplied by its coach count"
    )
    head_coach: DepartmentFinancialsEadaRole
    assistant_coach: DepartmentFinancialsEadaRole
    __properties: ClassVar[List[str]] = [
        "year",
        "total_salary_pool_cents",
        "head_coach",
        "assistant_coach",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DepartmentFinancialsEadaCoaching from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of head_coach
        if self.head_coach:
            _dict["head_coach"] = self.head_coach.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assistant_coach
        if self.assistant_coach:
            _dict["assistant_coach"] = self.assistant_coach.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DepartmentFinancialsEadaCoaching from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "year": obj.get("year"),
                "total_salary_pool_cents": obj.get("total_salary_pool_cents"),
                "head_coach": (
                    DepartmentFinancialsEadaRole.from_dict(obj["head_coach"])
                    if obj.get("head_coach") is not None
                    else None
                ),
                "assistant_coach": (
                    DepartmentFinancialsEadaRole.from_dict(obj["assistant_coach"])
                    if obj.get("assistant_coach") is not None
                    else None
                ),
            }
        )
        return _obj
