# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.70-dev.10297
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class DepartmentAdministratorsAdProfile(BaseModel):
    """
    Private-mode AD card — roster facts only, no money
    """  # noqa: E501

    coach_id: StrictInt
    friendly_id: Optional[StrictStr]
    name: StrictStr
    title: Optional[StrictStr]
    in_seat_since: Optional[date] = Field(
        description="Filed contract start date when one exists"
    )
    since_year: Optional[StrictInt] = Field(
        description="First season holding the AD position type at this school"
    )
    years_at_school: Optional[StrictInt]
    __properties: ClassVar[List[str]] = [
        "coach_id",
        "friendly_id",
        "name",
        "title",
        "in_seat_since",
        "since_year",
        "years_at_school",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DepartmentAdministratorsAdProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if friendly_id (nullable) is None
        # and model_fields_set contains the field
        if self.friendly_id is None and "friendly_id" in self.model_fields_set:
            _dict["friendly_id"] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict["title"] = None

        # set to None if in_seat_since (nullable) is None
        # and model_fields_set contains the field
        if self.in_seat_since is None and "in_seat_since" in self.model_fields_set:
            _dict["in_seat_since"] = None

        # set to None if since_year (nullable) is None
        # and model_fields_set contains the field
        if self.since_year is None and "since_year" in self.model_fields_set:
            _dict["since_year"] = None

        # set to None if years_at_school (nullable) is None
        # and model_fields_set contains the field
        if self.years_at_school is None and "years_at_school" in self.model_fields_set:
            _dict["years_at_school"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DepartmentAdministratorsAdProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "coach_id": obj.get("coach_id"),
                "friendly_id": obj.get("friendly_id"),
                "name": obj.get("name"),
                "title": obj.get("title"),
                "in_seat_since": obj.get("in_seat_since"),
                "since_year": obj.get("since_year"),
                "years_at_school": obj.get("years_at_school"),
            }
        )
        return _obj
