# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.66
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.department_overview_neighbour import (
    DepartmentOverviewNeighbour,
)
from typing import Optional, Set
from typing_extensions import Self


class DepartmentOverviewHeadlineStat(BaseModel):
    """
    DepartmentOverviewHeadlineStat
    """  # noqa: E501

    key: StrictStr
    label: StrictStr
    amount_cents: Optional[StrictInt]
    rank: Optional[StrictInt]
    cohort_size: StrictInt
    partial_cohort: StrictBool
    neighbour: Optional[DepartmentOverviewNeighbour]
    __properties: ClassVar[List[str]] = [
        "key",
        "label",
        "amount_cents",
        "rank",
        "cohort_size",
        "partial_cohort",
        "neighbour",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DepartmentOverviewHeadlineStat from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of neighbour
        if self.neighbour:
            _dict["neighbour"] = self.neighbour.to_dict()
        # set to None if amount_cents (nullable) is None
        # and model_fields_set contains the field
        if self.amount_cents is None and "amount_cents" in self.model_fields_set:
            _dict["amount_cents"] = None

        # set to None if rank (nullable) is None
        # and model_fields_set contains the field
        if self.rank is None and "rank" in self.model_fields_set:
            _dict["rank"] = None

        # set to None if neighbour (nullable) is None
        # and model_fields_set contains the field
        if self.neighbour is None and "neighbour" in self.model_fields_set:
            _dict["neighbour"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DepartmentOverviewHeadlineStat from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "key": obj.get("key"),
                "label": obj.get("label"),
                "amount_cents": obj.get("amount_cents"),
                "rank": obj.get("rank"),
                "cohort_size": obj.get("cohort_size"),
                "partial_cohort": obj.get("partial_cohort"),
                "neighbour": (
                    DepartmentOverviewNeighbour.from_dict(obj["neighbour"])
                    if obj.get("neighbour") is not None
                    else None
                ),
            }
        )
        return _obj
