# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.63
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self


class DepartmentAdministratorsStaffStats(BaseModel):
    """
    Percentiles over the filed annual amounts, PERCENTILE_CONT interpolation; null when comp is withheld or nothing is filed
    """  # noqa: E501

    with_comp_count: StrictInt
    median_cents: StrictInt
    p25_cents: StrictInt
    p75_cents: StrictInt
    mean_cents: StrictInt
    estimated: StrictBool = Field(
        description="True when 990 amounts are in the pool or some seats carry no comp"
    )
    __properties: ClassVar[List[str]] = [
        "with_comp_count",
        "median_cents",
        "p25_cents",
        "p75_cents",
        "mean_cents",
        "estimated",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DepartmentAdministratorsStaffStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DepartmentAdministratorsStaffStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "with_comp_count": obj.get("with_comp_count"),
                "median_cents": obj.get("median_cents"),
                "p25_cents": obj.get("p25_cents"),
                "p75_cents": obj.get("p75_cents"),
                "mean_cents": obj.get("mean_cents"),
                "estimated": obj.get("estimated"),
            }
        )
        return _obj
