# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.2-dev.10366
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self


class DepartmentGuaranteesSlateCoverage(BaseModel):
    """
    Coverage of the season's non-conference slate (WINAD-10394): the scheduling module's non-conference games for the season plus every ledger agreement whose game the schedule does not carry. A scheduled game is documented when an agreement the ledger lists backs it — by the schedule's link, or by describing the same dated game (sport, the two schools in either order, date) — and a game known only from its agreement is documented by definition, so documented_count never falls below the distinct games the ledger lists. A link to an agreement the ledger does not carry (cancelled, another season's, a tournament deal) documents nothing. private_vs_private_count is the undocumented games against a private opponent — the ones no public filing could ever recover. Null when nothing is scheduled and nothing is on file.
    """  # noqa: E501

    game_count: StrictInt
    documented_count: StrictInt
    private_vs_private_count: StrictInt
    __properties: ClassVar[List[str]] = [
        "game_count",
        "documented_count",
        "private_vs_private_count",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DepartmentGuaranteesSlateCoverage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DepartmentGuaranteesSlateCoverage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "game_count": obj.get("game_count"),
                "documented_count": obj.get("documented_count"),
                "private_vs_private_count": obj.get("private_vs_private_count"),
            }
        )
        return _obj
