# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.desk_html_file import DeskHtmlFile
from typing import Optional, Set
from typing_extensions import Self


class DeskComposition(BaseModel):
    """
    DeskComposition
    """  # noqa: E501

    cover_html: Optional[StrictStr] = Field(
        default=None,
        description="Cover theme HTML; only supported background and text styles are used. Visible text comes from report metadata. Draft covers may be cleared. A published cover cannot be replaced with null or blank text; an unchanged missing legacy cover is preserved. ",
    )
    cover_file: Optional[DeskHtmlFile] = None
    report_file: Optional[DeskHtmlFile] = None
    recipient_user_ids: Optional[List[StrictInt]] = Field(
        default=None,
        description="Null means everyone on the account; empty means admin only; IDs must belong to the account",
    )
    __properties: ClassVar[List[str]] = [
        "cover_html",
        "cover_file",
        "report_file",
        "recipient_user_ids",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeskComposition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cover_file
        if self.cover_file:
            _dict["cover_file"] = self.cover_file.to_dict()
        # override the default output from pydantic by calling `to_dict()` of report_file
        if self.report_file:
            _dict["report_file"] = self.report_file.to_dict()
        # set to None if cover_html (nullable) is None
        # and model_fields_set contains the field
        if self.cover_html is None and "cover_html" in self.model_fields_set:
            _dict["cover_html"] = None

        # set to None if cover_file (nullable) is None
        # and model_fields_set contains the field
        if self.cover_file is None and "cover_file" in self.model_fields_set:
            _dict["cover_file"] = None

        # set to None if report_file (nullable) is None
        # and model_fields_set contains the field
        if self.report_file is None and "report_file" in self.model_fields_set:
            _dict["report_file"] = None

        # set to None if recipient_user_ids (nullable) is None
        # and model_fields_set contains the field
        if (
            self.recipient_user_ids is None
            and "recipient_user_ids" in self.model_fields_set
        ):
            _dict["recipient_user_ids"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeskComposition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "cover_html": obj.get("cover_html"),
                "cover_file": (
                    DeskHtmlFile.from_dict(obj["cover_file"])
                    if obj.get("cover_file") is not None
                    else None
                ),
                "report_file": (
                    DeskHtmlFile.from_dict(obj["report_file"])
                    if obj.get("report_file") is not None
                    else None
                ),
                "recipient_user_ids": obj.get("recipient_user_ids"),
            }
        )
        return _obj
