# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.2-dev.10470
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class DeskAdminReportMetadata(BaseModel):
    """
    DeskAdminReportMetadata
    """  # noqa: E501

    title: Optional[Annotated[str, Field(strict=True, max_length=40)]] = None
    category: Optional[StrictStr] = None
    report_type: Optional[StrictStr] = None
    summary: Optional[Annotated[str, Field(strict=True, max_length=150)]] = None
    cover_treatment: Optional[StrictStr] = None
    cover_kicker: Optional[StrictStr] = Field(
        default=None,
        description='Defaults to "THE DESK · PREPARED FOR <ACCOUNT>" on create',
    )
    cover_numeral: Optional[Annotated[str, Field(strict=True, max_length=2)]] = Field(
        default=None, description='Decorative corner mark ("24", "AD"); blank clears it'
    )
    page_count: Optional[StrictInt] = None
    push_example: Optional[StrictStr] = None
    rerun_cadence: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "title",
        "category",
        "report_type",
        "summary",
        "cover_treatment",
        "cover_kicker",
        "cover_numeral",
        "page_count",
        "push_example",
        "rerun_cadence",
    ]

    @field_validator("category")
    def category_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["Financials", "Coaching", "Vendors", "Administrators"]):
            raise ValueError(
                "must be one of enum values ('Financials', 'Coaching', 'Vendors', 'Administrators')"
            )
        return value

    @field_validator("report_type")
    def report_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(
            [
                "intelligence_brief",
                "wcci",
                "staff_comp",
                "vendor_book",
                "financial",
                "budget_proposal",
                "buyout",
                "decision_brief",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('intelligence_brief', 'wcci', 'staff_comp', 'vendor_book', 'financial', 'budget_proposal', 'buyout', 'decision_brief')"
            )
        return value

    @field_validator("cover_treatment")
    def cover_treatment_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["ink", "oxblood", "bone"]):
            raise ValueError("must be one of enum values ('ink', 'oxblood', 'bone')")
        return value

    @field_validator("rerun_cadence")
    def rerun_cadence_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["off", "quarterly", "on_new_filing", "on_new_deal"]):
            raise ValueError(
                "must be one of enum values ('off', 'quarterly', 'on_new_filing', 'on_new_deal')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeskAdminReportMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if summary (nullable) is None
        # and model_fields_set contains the field
        if self.summary is None and "summary" in self.model_fields_set:
            _dict["summary"] = None

        # set to None if cover_kicker (nullable) is None
        # and model_fields_set contains the field
        if self.cover_kicker is None and "cover_kicker" in self.model_fields_set:
            _dict["cover_kicker"] = None

        # set to None if cover_numeral (nullable) is None
        # and model_fields_set contains the field
        if self.cover_numeral is None and "cover_numeral" in self.model_fields_set:
            _dict["cover_numeral"] = None

        # set to None if page_count (nullable) is None
        # and model_fields_set contains the field
        if self.page_count is None and "page_count" in self.model_fields_set:
            _dict["page_count"] = None

        # set to None if push_example (nullable) is None
        # and model_fields_set contains the field
        if self.push_example is None and "push_example" in self.model_fields_set:
            _dict["push_example"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeskAdminReportMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "title": obj.get("title"),
                "category": obj.get("category"),
                "report_type": obj.get("report_type"),
                "summary": obj.get("summary"),
                "cover_treatment": obj.get("cover_treatment"),
                "cover_kicker": obj.get("cover_kicker"),
                "cover_numeral": obj.get("cover_numeral"),
                "page_count": obj.get("page_count"),
                "push_example": obj.get("push_example"),
                "rerun_cadence": obj.get("rerun_cadence"),
            }
        )
        return _obj
