# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.30120408026
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from winthrop_client_python.models.foia_inbox_expected_compensation import (
    FoiaInboxExpectedCompensation,
)
from winthrop_client_python.models.foia_inbox_expected_requested_item import (
    FoiaInboxExpectedRequestedItem,
)
from typing import Optional, Set
from typing_extensions import Self


class FoiaInboxCompensationException(BaseModel):
    """
    FoiaInboxCompensationException
    """  # noqa: E501

    requested_item_id: StrictInt
    role: StrictStr
    actions: List[StrictStr]
    expected_requested_item: FoiaInboxExpectedRequestedItem
    expected_compensation: FoiaInboxExpectedCompensation
    __properties: ClassVar[List[str]] = [
        "requested_item_id",
        "role",
        "actions",
        "expected_requested_item",
        "expected_compensation",
    ]

    @field_validator("role")
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            [
                "volunteer",
                "graduate_assistant",
                "foundation_employee",
                "third_party_contractor",
                "not_employed",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('volunteer', 'graduate_assistant', 'foundation_employee', 'third_party_contractor', 'not_employed')"
            )
        return value

    @field_validator("actions")
    def actions_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(
                [
                    "update_requested_item_status",
                    "add_requested_item_note",
                    "update_compensation_status",
                    "add_compensation_note",
                    "add_position_type",
                ]
            ):
                raise ValueError(
                    "each list item must be one of ('update_requested_item_status', 'add_requested_item_note', 'update_compensation_status', 'add_compensation_note', 'add_position_type')"
                )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FoiaInboxCompensationException from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of expected_requested_item
        if self.expected_requested_item:
            _dict["expected_requested_item"] = self.expected_requested_item.to_dict()
        # override the default output from pydantic by calling `to_dict()` of expected_compensation
        if self.expected_compensation:
            _dict["expected_compensation"] = self.expected_compensation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FoiaInboxCompensationException from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "requested_item_id": obj.get("requested_item_id"),
                "role": obj.get("role"),
                "actions": obj.get("actions"),
                "expected_requested_item": (
                    FoiaInboxExpectedRequestedItem.from_dict(
                        obj["expected_requested_item"]
                    )
                    if obj.get("expected_requested_item") is not None
                    else None
                ),
                "expected_compensation": (
                    FoiaInboxExpectedCompensation.from_dict(
                        obj["expected_compensation"]
                    )
                    if obj.get("expected_compensation") is not None
                    else None
                ),
            }
        )
        return _obj
