# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.29247014805
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.foia_follow_up_requestable_data import (
    FoiaFollowUpRequestableData,
)
from typing import Optional, Set
from typing_extensions import Self


class FoiaFollowUpRequestedItem(BaseModel):
    """
    FoiaFollowUpRequestedItem
    """  # noqa: E501

    requested_item_id: Optional[StrictInt] = None
    requestable_type: Optional[StrictStr] = None
    requestable_id: Optional[StrictInt] = None
    requestable_data: Optional[FoiaFollowUpRequestableData] = None
    type_display: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    status_changed_at: Optional[datetime] = None
    previous_status: Optional[StrictStr] = None
    received_at: Optional[datetime] = None
    coach_id: Optional[StrictInt] = None
    coach_name: Optional[StrictStr] = None
    ri_note_id: Optional[StrictInt] = None
    note: Optional[StrictStr] = None
    note_updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = [
        "requested_item_id",
        "requestable_type",
        "requestable_id",
        "requestable_data",
        "type_display",
        "title",
        "status",
        "created_at",
        "updated_at",
        "status_changed_at",
        "previous_status",
        "received_at",
        "coach_id",
        "coach_name",
        "ri_note_id",
        "note",
        "note_updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FoiaFollowUpRequestedItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of requestable_data
        if self.requestable_data:
            _dict["requestable_data"] = self.requestable_data.to_dict()
        # set to None if requestable_type (nullable) is None
        # and model_fields_set contains the field
        if (
            self.requestable_type is None
            and "requestable_type" in self.model_fields_set
        ):
            _dict["requestable_type"] = None

        # set to None if requestable_id (nullable) is None
        # and model_fields_set contains the field
        if self.requestable_id is None and "requestable_id" in self.model_fields_set:
            _dict["requestable_id"] = None

        # set to None if status_changed_at (nullable) is None
        # and model_fields_set contains the field
        if (
            self.status_changed_at is None
            and "status_changed_at" in self.model_fields_set
        ):
            _dict["status_changed_at"] = None

        # set to None if previous_status (nullable) is None
        # and model_fields_set contains the field
        if self.previous_status is None and "previous_status" in self.model_fields_set:
            _dict["previous_status"] = None

        # set to None if received_at (nullable) is None
        # and model_fields_set contains the field
        if self.received_at is None and "received_at" in self.model_fields_set:
            _dict["received_at"] = None

        # set to None if coach_id (nullable) is None
        # and model_fields_set contains the field
        if self.coach_id is None and "coach_id" in self.model_fields_set:
            _dict["coach_id"] = None

        # set to None if coach_name (nullable) is None
        # and model_fields_set contains the field
        if self.coach_name is None and "coach_name" in self.model_fields_set:
            _dict["coach_name"] = None

        # set to None if ri_note_id (nullable) is None
        # and model_fields_set contains the field
        if self.ri_note_id is None and "ri_note_id" in self.model_fields_set:
            _dict["ri_note_id"] = None

        # set to None if note (nullable) is None
        # and model_fields_set contains the field
        if self.note is None and "note" in self.model_fields_set:
            _dict["note"] = None

        # set to None if note_updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.note_updated_at is None and "note_updated_at" in self.model_fields_set:
            _dict["note_updated_at"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FoiaFollowUpRequestedItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "requested_item_id": obj.get("requested_item_id"),
                "requestable_type": obj.get("requestable_type"),
                "requestable_id": obj.get("requestable_id"),
                "requestable_data": (
                    FoiaFollowUpRequestableData.from_dict(obj["requestable_data"])
                    if obj.get("requestable_data") is not None
                    else None
                ),
                "type_display": obj.get("type_display"),
                "title": obj.get("title"),
                "status": obj.get("status"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "status_changed_at": obj.get("status_changed_at"),
                "previous_status": obj.get("previous_status"),
                "received_at": obj.get("received_at"),
                "coach_id": obj.get("coach_id"),
                "coach_name": obj.get("coach_name"),
                "ri_note_id": obj.get("ri_note_id"),
                "note": obj.get("note"),
                "note_updated_at": obj.get("note_updated_at"),
            }
        )
        return _obj
