# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.41
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.game_post_availability_collection_groups_inner_posts_inner import (
    GamePostAvailabilityCollectionGroupsInnerPostsInner,
)
from typing import Optional, Set
from typing_extensions import Self


class GamePostAvailabilityCollectionGroupsInner(BaseModel):
    """
    GamePostAvailabilityCollectionGroupsInner
    """  # noqa: E501

    key: Optional[StrictStr] = None
    count: Optional[StrictInt] = Field(
        default=None, description="Total posts in the bucket (subtitle count)"
    )
    posts: Optional[List[GamePostAvailabilityCollectionGroupsInnerPostsInner]] = None
    __properties: ClassVar[List[str]] = ["key", "count", "posts"]

    @field_validator("key")
    def key_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["host", "travel", "hnh", "mte", "any"]):
            raise ValueError(
                "must be one of enum values ('host', 'travel', 'hnh', 'mte', 'any')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GamePostAvailabilityCollectionGroupsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in posts (list)
        _items = []
        if self.posts:
            for _item_posts in self.posts:
                if _item_posts:
                    _items.append(_item_posts.to_dict())
            _dict["posts"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GamePostAvailabilityCollectionGroupsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "key": obj.get("key"),
                "count": obj.get("count"),
                "posts": (
                    [
                        GamePostAvailabilityCollectionGroupsInnerPostsInner.from_dict(
                            _item
                        )
                        for _item in obj["posts"]
                    ]
                    if obj.get("posts") is not None
                    else None
                ),
            }
        )
        return _obj
