# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.id_name import IdName
from typing import Optional, Set
from typing_extensions import Self


class GetLadFilterOptions200Response(BaseModel):
    """
    GetLadFilterOptions200Response
    """  # noqa: E501

    position_types: Optional[List[IdName]] = None
    departments: Optional[List[IdName]] = None
    school_groups: Optional[List[IdName]] = None
    __properties: ClassVar[List[str]] = [
        "position_types",
        "departments",
        "school_groups",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetLadFilterOptions200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in position_types (list)
        _items = []
        if self.position_types:
            for _item_position_types in self.position_types:
                if _item_position_types:
                    _items.append(_item_position_types.to_dict())
            _dict["position_types"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in departments (list)
        _items = []
        if self.departments:
            for _item_departments in self.departments:
                if _item_departments:
                    _items.append(_item_departments.to_dict())
            _dict["departments"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in school_groups (list)
        _items = []
        if self.school_groups:
            for _item_school_groups in self.school_groups:
                if _item_school_groups:
                    _items.append(_item_school_groups.to_dict())
            _dict["school_groups"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetLadFilterOptions200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "position_types": (
                    [IdName.from_dict(_item) for _item in obj["position_types"]]
                    if obj.get("position_types") is not None
                    else None
                ),
                "departments": (
                    [IdName.from_dict(_item) for _item in obj["departments"]]
                    if obj.get("departments") is not None
                    else None
                ),
                "school_groups": (
                    [IdName.from_dict(_item) for _item in obj["school_groups"]]
                    if obj.get("school_groups") is not None
                    else None
                ),
            }
        )
        return _obj
