# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.73-dev.10297
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class NcaaFinancialReportItemValue(BaseModel):
    """
    NcaaFinancialReportItemValue
    """  # noqa: E501

    item_number: StrictStr
    line_item: StrictStr
    section: StrictStr
    value_kind: StrictStr
    raw_value: StrictStr
    numeric_value: Optional[StrictStr] = Field(
        default=None,
        description="Exact decimal representation for currency and decimal values.",
    )
    text_value: Optional[StrictStr] = None
    reporting_status: StrictStr
    display_value: StrictStr
    position: StrictInt
    __properties: ClassVar[List[str]] = [
        "item_number",
        "line_item",
        "section",
        "value_kind",
        "raw_value",
        "numeric_value",
        "text_value",
        "reporting_status",
        "display_value",
        "position",
    ]

    @field_validator("value_kind")
    def value_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["currency", "decimal", "text"]):
            raise ValueError(
                "must be one of enum values ('currency', 'decimal', 'text')"
            )
        return value

    @field_validator("reporting_status")
    def reporting_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            ["reported", "blank", "not_applicable", "missing", "unparsed"]
        ):
            raise ValueError(
                "must be one of enum values ('reported', 'blank', 'not_applicable', 'missing', 'unparsed')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NcaaFinancialReportItemValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if numeric_value (nullable) is None
        # and model_fields_set contains the field
        if self.numeric_value is None and "numeric_value" in self.model_fields_set:
            _dict["numeric_value"] = None

        # set to None if text_value (nullable) is None
        # and model_fields_set contains the field
        if self.text_value is None and "text_value" in self.model_fields_set:
            _dict["text_value"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NcaaFinancialReportItemValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "item_number": obj.get("item_number"),
                "line_item": obj.get("line_item"),
                "section": obj.get("section"),
                "value_kind": obj.get("value_kind"),
                "raw_value": obj.get("raw_value"),
                "numeric_value": obj.get("numeric_value"),
                "text_value": obj.get("text_value"),
                "reporting_status": obj.get("reporting_status"),
                "display_value": obj.get("display_value"),
                "position": obj.get("position"),
            }
        )
        return _obj
