# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.69-dev.10283
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class NcaaFinancialStat(BaseModel):
    """
    NcaaFinancialStat
    """  # noqa: E501

    sport_id: StrictInt
    sport_name: StrictStr
    gender_code: Optional[StrictStr]
    source_sport_name: Optional[StrictStr]
    raw_contract_id: StrictInt
    athletic_aid_equivalency: Optional[StrictStr] = Field(
        description="Exact decimal representation of item 20 Part A."
    )
    exhausted_eligibility_or_medical_equivalency: Optional[StrictStr] = Field(
        description="Exact decimal representation of item 20 Part B."
    )
    equivalencies_awarded: Optional[StrictStr] = Field(
        description="Exact decimal representation of item 20 Parts A and B combined."
    )
    students_receiving_athletic_aid: Optional[StrictInt]
    head_coach_positions: Optional[StrictInt]
    head_coach_fte: Optional[StrictStr] = Field(
        description="Exact decimal representation of item 22 head-coach FTE."
    )
    assistant_coach_positions: Optional[StrictInt]
    assistant_coach_fte: Optional[StrictStr] = Field(
        description="Exact decimal representation of item 22 assistant-coach FTE."
    )
    first_team_participants: Optional[StrictInt]
    second_team_participants: Optional[StrictInt]
    third_team_participants: Optional[StrictInt]
    __properties: ClassVar[List[str]] = [
        "sport_id",
        "sport_name",
        "gender_code",
        "source_sport_name",
        "raw_contract_id",
        "athletic_aid_equivalency",
        "exhausted_eligibility_or_medical_equivalency",
        "equivalencies_awarded",
        "students_receiving_athletic_aid",
        "head_coach_positions",
        "head_coach_fte",
        "assistant_coach_positions",
        "assistant_coach_fte",
        "first_team_participants",
        "second_team_participants",
        "third_team_participants",
    ]

    @field_validator("gender_code")
    def gender_code_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["M", "W"]):
            raise ValueError("must be one of enum values ('M', 'W')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NcaaFinancialStat from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if gender_code (nullable) is None
        # and model_fields_set contains the field
        if self.gender_code is None and "gender_code" in self.model_fields_set:
            _dict["gender_code"] = None

        # set to None if source_sport_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.source_sport_name is None
            and "source_sport_name" in self.model_fields_set
        ):
            _dict["source_sport_name"] = None

        # set to None if athletic_aid_equivalency (nullable) is None
        # and model_fields_set contains the field
        if (
            self.athletic_aid_equivalency is None
            and "athletic_aid_equivalency" in self.model_fields_set
        ):
            _dict["athletic_aid_equivalency"] = None

        # set to None if exhausted_eligibility_or_medical_equivalency (nullable) is None
        # and model_fields_set contains the field
        if (
            self.exhausted_eligibility_or_medical_equivalency is None
            and "exhausted_eligibility_or_medical_equivalency" in self.model_fields_set
        ):
            _dict["exhausted_eligibility_or_medical_equivalency"] = None

        # set to None if equivalencies_awarded (nullable) is None
        # and model_fields_set contains the field
        if (
            self.equivalencies_awarded is None
            and "equivalencies_awarded" in self.model_fields_set
        ):
            _dict["equivalencies_awarded"] = None

        # set to None if students_receiving_athletic_aid (nullable) is None
        # and model_fields_set contains the field
        if (
            self.students_receiving_athletic_aid is None
            and "students_receiving_athletic_aid" in self.model_fields_set
        ):
            _dict["students_receiving_athletic_aid"] = None

        # set to None if head_coach_positions (nullable) is None
        # and model_fields_set contains the field
        if (
            self.head_coach_positions is None
            and "head_coach_positions" in self.model_fields_set
        ):
            _dict["head_coach_positions"] = None

        # set to None if head_coach_fte (nullable) is None
        # and model_fields_set contains the field
        if self.head_coach_fte is None and "head_coach_fte" in self.model_fields_set:
            _dict["head_coach_fte"] = None

        # set to None if assistant_coach_positions (nullable) is None
        # and model_fields_set contains the field
        if (
            self.assistant_coach_positions is None
            and "assistant_coach_positions" in self.model_fields_set
        ):
            _dict["assistant_coach_positions"] = None

        # set to None if assistant_coach_fte (nullable) is None
        # and model_fields_set contains the field
        if (
            self.assistant_coach_fte is None
            and "assistant_coach_fte" in self.model_fields_set
        ):
            _dict["assistant_coach_fte"] = None

        # set to None if first_team_participants (nullable) is None
        # and model_fields_set contains the field
        if (
            self.first_team_participants is None
            and "first_team_participants" in self.model_fields_set
        ):
            _dict["first_team_participants"] = None

        # set to None if second_team_participants (nullable) is None
        # and model_fields_set contains the field
        if (
            self.second_team_participants is None
            and "second_team_participants" in self.model_fields_set
        ):
            _dict["second_team_participants"] = None

        # set to None if third_team_participants (nullable) is None
        # and model_fields_set contains the field
        if (
            self.third_team_participants is None
            and "third_team_participants" in self.model_fields_set
        ):
            _dict["third_team_participants"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NcaaFinancialStat from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "sport_id": obj.get("sport_id"),
                "sport_name": obj.get("sport_name"),
                "gender_code": obj.get("gender_code"),
                "source_sport_name": obj.get("source_sport_name"),
                "raw_contract_id": obj.get("raw_contract_id"),
                "athletic_aid_equivalency": obj.get("athletic_aid_equivalency"),
                "exhausted_eligibility_or_medical_equivalency": obj.get(
                    "exhausted_eligibility_or_medical_equivalency"
                ),
                "equivalencies_awarded": obj.get("equivalencies_awarded"),
                "students_receiving_athletic_aid": obj.get(
                    "students_receiving_athletic_aid"
                ),
                "head_coach_positions": obj.get("head_coach_positions"),
                "head_coach_fte": obj.get("head_coach_fte"),
                "assistant_coach_positions": obj.get("assistant_coach_positions"),
                "assistant_coach_fte": obj.get("assistant_coach_fte"),
                "first_team_participants": obj.get("first_team_participants"),
                "second_team_participants": obj.get("second_team_participants"),
                "third_team_participants": obj.get("third_team_participants"),
            }
        )
        return _obj
