# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.47
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class RequestedItemReviewContextDocument(BaseModel):
    """
    RequestedItemReviewContextDocument
    """  # noqa: E501

    id: StrictInt = Field(
        description="Raw contract (document) ID for duplicate and review checks."
    )
    label: StrictStr = Field(description="Canonical WinAD document label.")
    has_file: StrictBool = Field(
        description="True when the document has a non-empty attached file."
    )
    file_name: Optional[StrictStr] = Field(
        description="Attached file name; null when has_file is false."
    )
    content_type: Optional[StrictStr]
    byte_size: Optional[StrictInt] = Field(
        description="Attached file size in bytes; null when has_file is false."
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "label",
        "has_file",
        "file_name",
        "content_type",
        "byte_size",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RequestedItemReviewContextDocument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if file_name (nullable) is None
        # and model_fields_set contains the field
        if self.file_name is None and "file_name" in self.model_fields_set:
            _dict["file_name"] = None

        # set to None if content_type (nullable) is None
        # and model_fields_set contains the field
        if self.content_type is None and "content_type" in self.model_fields_set:
            _dict["content_type"] = None

        # set to None if byte_size (nullable) is None
        # and model_fields_set contains the field
        if self.byte_size is None and "byte_size" in self.model_fields_set:
            _dict["byte_size"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RequestedItemReviewContextDocument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "label": obj.get("label"),
                "has_file": obj.get("has_file"),
                "file_name": obj.get("file_name"),
                "content_type": obj.get("content_type"),
                "byte_size": obj.get("byte_size"),
            }
        )
        return _obj
