# coding: utf-8

"""
    Winthrop Intelligence Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, validator


class RequestedItem(BaseModel):
    """
    RequestedItem
    """

    id: Optional[StrictInt] = None
    foia_request_id: StrictInt = Field(...)
    requestable_id: StrictInt = Field(...)
    requestable_type: StrictStr = Field(...)
    received: Optional[StrictBool] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    coach_id: Optional[StrictInt] = None
    status: Optional[StrictStr] = None
    __properties = [
        "id",
        "foia_request_id",
        "requestable_id",
        "requestable_type",
        "received",
        "created_at",
        "updated_at",
        "coach_id",
        "status",
    ]

    @validator("requestable_type")
    def requestable_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in (
            "DealStatus",
            "Game",
            "Compensation",
            "IncomeReport",
            "NcaaFinancialReportStatus",
            "AuditedFinancialReportStatus",
        ):
            raise ValueError(
                "must be one of enum values ('DealStatus', 'Game', 'Compensation', 'IncomeReport', 'NcaaFinancialReportStatus', 'AuditedFinancialReportStatus')"
            )
        return value

    @validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("pending", "not_available", "received"):
            raise ValueError(
                "must be one of enum values ('pending', 'not_available', 'received')"
            )
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RequestedItem:
        """Create an instance of RequestedItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RequestedItem:
        """Create an instance of RequestedItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RequestedItem.parse_obj(obj)

        _obj = RequestedItem.parse_obj(
            {
                "id": obj.get("id"),
                "foia_request_id": obj.get("foia_request_id"),
                "requestable_id": obj.get("requestable_id"),
                "requestable_type": obj.get("requestable_type"),
                "received": obj.get("received"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "coach_id": obj.get("coach_id"),
                "status": obj.get("status"),
            }
        )
        return _obj
