# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.schedule_grid_available_school_post import (
    ScheduleGridAvailableSchoolPost,
)
from typing import Optional, Set
from typing_extensions import Self


class ScheduleGridAvailableSchoolRow(BaseModel):
    """
    Candidate school returned by the available-schools finder
    """  # noqa: E501

    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    short_name: Optional[StrictStr] = None
    logo_url: Optional[StrictStr] = None
    primary_contact_name: Optional[StrictStr] = None
    primary_contact_phone: Optional[StrictStr] = None
    subdivision_name: Optional[StrictStr] = None
    rank: Optional[StrictInt] = Field(
        default=None, description="Current USNWR ranking (omitted when blank)"
    )
    distance_miles: Optional[StrictInt] = Field(
        default=None,
        description="Distance from user_school_id in miles (omitted when distance filtering is not active)",
    )
    nearest_post: Optional[ScheduleGridAvailableSchoolPost] = Field(
        default=None,
        description="Nearest active GamePost to target_date in the window. Null when the school has no openness recorded for the window (assumed-eligible).",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "short_name",
        "logo_url",
        "primary_contact_name",
        "primary_contact_phone",
        "subdivision_name",
        "rank",
        "distance_miles",
        "nearest_post",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScheduleGridAvailableSchoolRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of nearest_post
        if self.nearest_post:
            _dict["nearest_post"] = self.nearest_post.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict["name"] = None

        # set to None if short_name (nullable) is None
        # and model_fields_set contains the field
        if self.short_name is None and "short_name" in self.model_fields_set:
            _dict["short_name"] = None

        # set to None if logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.logo_url is None and "logo_url" in self.model_fields_set:
            _dict["logo_url"] = None

        # set to None if primary_contact_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.primary_contact_name is None
            and "primary_contact_name" in self.model_fields_set
        ):
            _dict["primary_contact_name"] = None

        # set to None if primary_contact_phone (nullable) is None
        # and model_fields_set contains the field
        if (
            self.primary_contact_phone is None
            and "primary_contact_phone" in self.model_fields_set
        ):
            _dict["primary_contact_phone"] = None

        # set to None if subdivision_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.subdivision_name is None
            and "subdivision_name" in self.model_fields_set
        ):
            _dict["subdivision_name"] = None

        # set to None if rank (nullable) is None
        # and model_fields_set contains the field
        if self.rank is None and "rank" in self.model_fields_set:
            _dict["rank"] = None

        # set to None if distance_miles (nullable) is None
        # and model_fields_set contains the field
        if self.distance_miles is None and "distance_miles" in self.model_fields_set:
            _dict["distance_miles"] = None

        # set to None if nearest_post (nullable) is None
        # and model_fields_set contains the field
        if self.nearest_post is None and "nearest_post" in self.model_fields_set:
            _dict["nearest_post"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScheduleGridAvailableSchoolRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "short_name": obj.get("short_name"),
                "logo_url": obj.get("logo_url"),
                "primary_contact_name": obj.get("primary_contact_name"),
                "primary_contact_phone": obj.get("primary_contact_phone"),
                "subdivision_name": obj.get("subdivision_name"),
                "rank": obj.get("rank"),
                "distance_miles": obj.get("distance_miles"),
                "nearest_post": (
                    ScheduleGridAvailableSchoolPost.from_dict(obj["nearest_post"])
                    if obj.get("nearest_post") is not None
                    else None
                ),
            }
        )
        return _obj
