# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.65-dev.10252
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.department_guarantees_committed_side import (
    DepartmentGuaranteesCommittedSide,
)
from winthrop_client_python.models.department_guarantees_filed_line import (
    DepartmentGuaranteesFiledLine,
)
from winthrop_client_python.models.department_guarantees_market import (
    DepartmentGuaranteesMarket,
)
from winthrop_client_python.models.department_guarantees_quadrant import (
    DepartmentGuaranteesQuadrant,
)
from winthrop_client_python.models.department_guarantees_sport_ledger import (
    DepartmentGuaranteesSportLedger,
)
from winthrop_client_python.models.department_guarantees_trend_entry import (
    DepartmentGuaranteesTrendEntry,
)
from winthrop_client_python.models.school_department_guarantees_school import (
    SchoolDepartmentGuaranteesSchool,
)
from winthrop_client_python.models.school_department_overview_conference import (
    SchoolDepartmentOverviewConference,
)
from typing import Optional, Set
from typing_extensions import Self


class SchoolDepartmentGuarantees(BaseModel):
    """
    SchoolDepartmentGuarantees
    """  # noqa: E501

    school: SchoolDepartmentGuaranteesSchool
    conference: Optional[SchoolDepartmentOverviewConference]
    season_year: StrictInt
    latest_filed_year: Optional[StrictInt]
    selected_year: Optional[StrictInt]
    available_years: List[StrictInt]
    quadrant: Optional[DepartmentGuaranteesQuadrant]
    filed_line: Optional[DepartmentGuaranteesFiledLine]
    committed_out: DepartmentGuaranteesCommittedSide
    committed_in: DepartmentGuaranteesCommittedSide
    sports: List[DepartmentGuaranteesSportLedger]
    market: Optional[DepartmentGuaranteesMarket]
    trend: List[DepartmentGuaranteesTrendEntry]
    __properties: ClassVar[List[str]] = [
        "school",
        "conference",
        "season_year",
        "latest_filed_year",
        "selected_year",
        "available_years",
        "quadrant",
        "filed_line",
        "committed_out",
        "committed_in",
        "sports",
        "market",
        "trend",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchoolDepartmentGuarantees from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of school
        if self.school:
            _dict["school"] = self.school.to_dict()
        # override the default output from pydantic by calling `to_dict()` of conference
        if self.conference:
            _dict["conference"] = self.conference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of quadrant
        if self.quadrant:
            _dict["quadrant"] = self.quadrant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filed_line
        if self.filed_line:
            _dict["filed_line"] = self.filed_line.to_dict()
        # override the default output from pydantic by calling `to_dict()` of committed_out
        if self.committed_out:
            _dict["committed_out"] = self.committed_out.to_dict()
        # override the default output from pydantic by calling `to_dict()` of committed_in
        if self.committed_in:
            _dict["committed_in"] = self.committed_in.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sports (list)
        _items = []
        if self.sports:
            for _item_sports in self.sports:
                if _item_sports:
                    _items.append(_item_sports.to_dict())
            _dict["sports"] = _items
        # override the default output from pydantic by calling `to_dict()` of market
        if self.market:
            _dict["market"] = self.market.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in trend (list)
        _items = []
        if self.trend:
            for _item_trend in self.trend:
                if _item_trend:
                    _items.append(_item_trend.to_dict())
            _dict["trend"] = _items
        # set to None if conference (nullable) is None
        # and model_fields_set contains the field
        if self.conference is None and "conference" in self.model_fields_set:
            _dict["conference"] = None

        # set to None if latest_filed_year (nullable) is None
        # and model_fields_set contains the field
        if (
            self.latest_filed_year is None
            and "latest_filed_year" in self.model_fields_set
        ):
            _dict["latest_filed_year"] = None

        # set to None if selected_year (nullable) is None
        # and model_fields_set contains the field
        if self.selected_year is None and "selected_year" in self.model_fields_set:
            _dict["selected_year"] = None

        # set to None if quadrant (nullable) is None
        # and model_fields_set contains the field
        if self.quadrant is None and "quadrant" in self.model_fields_set:
            _dict["quadrant"] = None

        # set to None if filed_line (nullable) is None
        # and model_fields_set contains the field
        if self.filed_line is None and "filed_line" in self.model_fields_set:
            _dict["filed_line"] = None

        # set to None if market (nullable) is None
        # and model_fields_set contains the field
        if self.market is None and "market" in self.model_fields_set:
            _dict["market"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchoolDepartmentGuarantees from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "school": (
                    SchoolDepartmentGuaranteesSchool.from_dict(obj["school"])
                    if obj.get("school") is not None
                    else None
                ),
                "conference": (
                    SchoolDepartmentOverviewConference.from_dict(obj["conference"])
                    if obj.get("conference") is not None
                    else None
                ),
                "season_year": obj.get("season_year"),
                "latest_filed_year": obj.get("latest_filed_year"),
                "selected_year": obj.get("selected_year"),
                "available_years": obj.get("available_years"),
                "quadrant": (
                    DepartmentGuaranteesQuadrant.from_dict(obj["quadrant"])
                    if obj.get("quadrant") is not None
                    else None
                ),
                "filed_line": (
                    DepartmentGuaranteesFiledLine.from_dict(obj["filed_line"])
                    if obj.get("filed_line") is not None
                    else None
                ),
                "committed_out": (
                    DepartmentGuaranteesCommittedSide.from_dict(obj["committed_out"])
                    if obj.get("committed_out") is not None
                    else None
                ),
                "committed_in": (
                    DepartmentGuaranteesCommittedSide.from_dict(obj["committed_in"])
                    if obj.get("committed_in") is not None
                    else None
                ),
                "sports": (
                    [
                        DepartmentGuaranteesSportLedger.from_dict(_item)
                        for _item in obj["sports"]
                    ]
                    if obj.get("sports") is not None
                    else None
                ),
                "market": (
                    DepartmentGuaranteesMarket.from_dict(obj["market"])
                    if obj.get("market") is not None
                    else None
                ),
                "trend": (
                    [
                        DepartmentGuaranteesTrendEntry.from_dict(_item)
                        for _item in obj["trend"]
                    ]
                    if obj.get("trend") is not None
                    else None
                ),
            }
        )
        return _obj
