# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.school_contract_entry import SchoolContractEntry
from winthrop_client_python.models.school_sport_season import SchoolSportSeason
from winthrop_client_python.models.school_wl_chart_point import SchoolWLChartPoint
from typing import Optional, Set
from typing_extensions import Self


class SchoolSportSection(BaseModel):
    """
    SchoolSportSection
    """  # noqa: E501

    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    average_attendance: Optional[float] = None
    pays_average_cents: Optional[StrictInt] = None
    receives_average_cents: Optional[StrictInt] = None
    seasons: Optional[List[SchoolSportSeason]] = None
    wl_chart: Optional[List[SchoolWLChartPoint]] = None
    home_contracts: Optional[List[SchoolContractEntry]] = None
    away_contracts: Optional[List[SchoolContractEntry]] = None
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "average_attendance",
        "pays_average_cents",
        "receives_average_cents",
        "seasons",
        "wl_chart",
        "home_contracts",
        "away_contracts",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchoolSportSection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in seasons (list)
        _items = []
        if self.seasons:
            for _item_seasons in self.seasons:
                if _item_seasons:
                    _items.append(_item_seasons.to_dict())
            _dict["seasons"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in wl_chart (list)
        _items = []
        if self.wl_chart:
            for _item_wl_chart in self.wl_chart:
                if _item_wl_chart:
                    _items.append(_item_wl_chart.to_dict())
            _dict["wl_chart"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in home_contracts (list)
        _items = []
        if self.home_contracts:
            for _item_home_contracts in self.home_contracts:
                if _item_home_contracts:
                    _items.append(_item_home_contracts.to_dict())
            _dict["home_contracts"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in away_contracts (list)
        _items = []
        if self.away_contracts:
            for _item_away_contracts in self.away_contracts:
                if _item_away_contracts:
                    _items.append(_item_away_contracts.to_dict())
            _dict["away_contracts"] = _items
        # set to None if average_attendance (nullable) is None
        # and model_fields_set contains the field
        if (
            self.average_attendance is None
            and "average_attendance" in self.model_fields_set
        ):
            _dict["average_attendance"] = None

        # set to None if pays_average_cents (nullable) is None
        # and model_fields_set contains the field
        if (
            self.pays_average_cents is None
            and "pays_average_cents" in self.model_fields_set
        ):
            _dict["pays_average_cents"] = None

        # set to None if receives_average_cents (nullable) is None
        # and model_fields_set contains the field
        if (
            self.receives_average_cents is None
            and "receives_average_cents" in self.model_fields_set
        ):
            _dict["receives_average_cents"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchoolSportSection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "average_attendance": obj.get("average_attendance"),
                "pays_average_cents": obj.get("pays_average_cents"),
                "receives_average_cents": obj.get("receives_average_cents"),
                "seasons": (
                    [SchoolSportSeason.from_dict(_item) for _item in obj["seasons"]]
                    if obj.get("seasons") is not None
                    else None
                ),
                "wl_chart": (
                    [SchoolWLChartPoint.from_dict(_item) for _item in obj["wl_chart"]]
                    if obj.get("wl_chart") is not None
                    else None
                ),
                "home_contracts": (
                    [
                        SchoolContractEntry.from_dict(_item)
                        for _item in obj["home_contracts"]
                    ]
                    if obj.get("home_contracts") is not None
                    else None
                ),
                "away_contracts": (
                    [
                        SchoolContractEntry.from_dict(_item)
                        for _item in obj["away_contracts"]
                    ]
                    if obj.get("away_contracts") is not None
                    else None
                ),
            }
        )
        return _obj
