# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class TeamSchedulePlayerDataRecruitsInner(BaseModel):
    """
    TeamSchedulePlayerDataRecruitsInner
    """  # noqa: E501

    name: Optional[StrictStr] = None
    position: Optional[StrictStr] = None
    height: Optional[StrictStr] = None
    weight: Optional[float] = None
    average_stars: Optional[float] = None
    overall_ranking: Optional[float] = None
    position_ranking: Optional[float] = None
    __properties: ClassVar[List[str]] = [
        "name",
        "position",
        "height",
        "weight",
        "average_stars",
        "overall_ranking",
        "position_ranking",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TeamSchedulePlayerDataRecruitsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if position (nullable) is None
        # and model_fields_set contains the field
        if self.position is None and "position" in self.model_fields_set:
            _dict["position"] = None

        # set to None if height (nullable) is None
        # and model_fields_set contains the field
        if self.height is None and "height" in self.model_fields_set:
            _dict["height"] = None

        # set to None if weight (nullable) is None
        # and model_fields_set contains the field
        if self.weight is None and "weight" in self.model_fields_set:
            _dict["weight"] = None

        # set to None if average_stars (nullable) is None
        # and model_fields_set contains the field
        if self.average_stars is None and "average_stars" in self.model_fields_set:
            _dict["average_stars"] = None

        # set to None if overall_ranking (nullable) is None
        # and model_fields_set contains the field
        if self.overall_ranking is None and "overall_ranking" in self.model_fields_set:
            _dict["overall_ranking"] = None

        # set to None if position_ranking (nullable) is None
        # and model_fields_set contains the field
        if (
            self.position_ranking is None
            and "position_ranking" in self.model_fields_set
        ):
            _dict["position_ranking"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TeamSchedulePlayerDataRecruitsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "position": obj.get("position"),
                "height": obj.get("height"),
                "weight": obj.get("weight"),
                "average_stars": obj.get("average_stars"),
                "overall_ranking": obj.get("overall_ranking"),
                "position_ranking": obj.get("position_ranking"),
            }
        )
        return _obj
