# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from winthrop_client_python.models.team_schedule_coaches_coaches_inner import (
    TeamScheduleCoachesCoachesInner,
)
from winthrop_client_python.models.team_schedule_coaches_head_coaches_inner_inner import (
    TeamScheduleCoachesHeadCoachesInnerInner,
)
from winthrop_client_python.models.team_schedule_coaches_seasons_inner import (
    TeamScheduleCoachesSeasonsInner,
)
from typing import Optional, Set
from typing_extensions import Self


class TeamScheduleCoaches(BaseModel):
    """
    TeamScheduleCoaches
    """  # noqa: E501

    performance_year: Optional[StrictInt] = None
    performance_years: Optional[List[StrictInt]] = None
    coaches: Optional[List[TeamScheduleCoachesCoachesInner]] = None
    head_coaches: Optional[List[List[TeamScheduleCoachesHeadCoachesInnerInner]]] = None
    seasons: Optional[List[Optional[TeamScheduleCoachesSeasonsInner]]] = None
    __properties: ClassVar[List[str]] = [
        "performance_year",
        "performance_years",
        "coaches",
        "head_coaches",
        "seasons",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TeamScheduleCoaches from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in coaches (list)
        _items = []
        if self.coaches:
            for _item_coaches in self.coaches:
                if _item_coaches:
                    _items.append(_item_coaches.to_dict())
            _dict["coaches"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in head_coaches (list of list)
        _items = []
        if self.head_coaches:
            for _item_head_coaches in self.head_coaches:
                if _item_head_coaches:
                    _items.append(
                        [
                            _inner_item.to_dict()
                            for _inner_item in _item_head_coaches
                            if _inner_item is not None
                        ]
                    )
            _dict["head_coaches"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in seasons (list)
        _items = []
        if self.seasons:
            for _item_seasons in self.seasons:
                if _item_seasons:
                    _items.append(_item_seasons.to_dict())
            _dict["seasons"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TeamScheduleCoaches from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "performance_year": obj.get("performance_year"),
                "performance_years": obj.get("performance_years"),
                "coaches": (
                    [
                        TeamScheduleCoachesCoachesInner.from_dict(_item)
                        for _item in obj["coaches"]
                    ]
                    if obj.get("coaches") is not None
                    else None
                ),
                "head_coaches": (
                    [
                        [
                            TeamScheduleCoachesHeadCoachesInnerInner.from_dict(
                                _inner_item
                            )
                            for _inner_item in _item
                        ]
                        for _item in obj["head_coaches"]
                    ]
                    if obj.get("head_coaches") is not None
                    else None
                ),
                "seasons": (
                    [
                        TeamScheduleCoachesSeasonsInner.from_dict(_item)
                        for _item in obj["seasons"]
                    ]
                    if obj.get("seasons") is not None
                    else None
                ),
            }
        )
        return _obj
