# coding: utf-8

"""
Winthrop Intelligence Internal API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.30-dev.9866
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class UpdateUserRequestUser(BaseModel):
    """
    UpdateUserRequestUser
    """  # noqa: E501

    first_name: Optional[StrictStr] = None
    last_name: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    time_zone: Optional[StrictStr] = None
    scheduling_phone: Optional[StrictStr] = None
    scheduling_notifications: Optional[StrictBool] = None
    game_post_notifications: Optional[StrictBool] = None
    games_digest: Optional[StrictBool] = None
    current_password: Optional[StrictStr] = None
    password: Optional[StrictStr] = None
    password_confirmation: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "first_name",
        "last_name",
        "email",
        "time_zone",
        "scheduling_phone",
        "scheduling_notifications",
        "game_post_notifications",
        "games_digest",
        "current_password",
        "password",
        "password_confirmation",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateUserRequestUser from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if scheduling_phone (nullable) is None
        # and model_fields_set contains the field
        if (
            self.scheduling_phone is None
            and "scheduling_phone" in self.model_fields_set
        ):
            _dict["scheduling_phone"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateUserRequestUser from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "first_name": obj.get("first_name"),
                "last_name": obj.get("last_name"),
                "email": obj.get("email"),
                "time_zone": obj.get("time_zone"),
                "scheduling_phone": obj.get("scheduling_phone"),
                "scheduling_notifications": obj.get("scheduling_notifications"),
                "game_post_notifications": obj.get("game_post_notifications"),
                "games_digest": obj.get("games_digest"),
                "current_password": obj.get("current_password"),
                "password": obj.get("password"),
                "password_confirmation": obj.get("password_confirmation"),
            }
        )
        return _obj
